export const airports = {
    AAA: "Anaa",
    AAC: "El Arish",
    AAE: "Annaba",
    AAL: "Aalborg",
    AAM: "Malamala",
    AAN: "Al Ain",
    AAO: "Anaco",
    AAP: "Samarinda",
    AAQ: "Krasnyi Kurgan",
    AAR: "Aarhus",
    AAT: "Altay",
    AAV: "Surallah",
    AAY: "Al Ghaydah",
    ABA: "Abakan",
    ABB: "Asaba",
    ABC: "Albacete",
    ABD: "Abadan",
    ABE: "Allentown",
    ABH: "Alpha",
    ABI: "Abilene",
    ABJ: "Abidjan",
    ABK: "Kebri Dahar",
    ABL: "Ambler",
    ABQ: "Albuquerque",
    ABR: "Aberdeen",
    ABS: "Abu Simbel",
    ABT: "Al Aqiq",
    ABV: "Abuja",
    ABX: "Albury",
    ABY: "Albany",
    ABZ: "Aberdeen",
    ACA: "Acapulco",
    ACC: "Accra",
    ACE: "Lanzarote Island",
    ACH: "Altenrhein",
    ACI: "Saint Anne",
    ACJ: "Anuradhapura",
    ACK: "Nantucket",
    ACS: "Achinsk",
    ACT: "Waco",
    ACV: "Arcata/Eureka",
    ACX: "Xingyi",
    ACY: "Atlantic City",
    ACZ: "Zabol",
    ADA: "Seyhan",
    ADB: "Ä°zmir",
    ADD: "Addis Ababa",
    ADE: "Aden",
    ADF: "AdÄ±yaman",
    ADI: "Arandis",
    ADJ: "Amman",
    ADK: "Adak",
    ADL: "Adelaide",
    ADP: "Ampara",
    ADQ: "Kodiak",
    ADU: "Ardabil",
    ADW: "Camp Springs",
    ADX: "Leuchars, Fife",
    ADZ: "San AndrÃ©s",
    AEB: "Baise (Tianyang)",
    AEG: "Padang Sidempuan",
    AEH: "Abeche",
    AEP: "Buenos Aires",
    AER: "Sochi",
    AES: "Ã…lesund",
    AEU: "Abu Musa",
    AEX: "Alexandria",
    AEY: "Akureyri",
    AFA: "San Rafael",
    AFL: "Alta Floresta",
    AFW: "Fort Worth",
    AFY: "Afyonkarahisar",
    AFZ: "Sabzevar",
    AGA: "Agadir (Temsia)",
    AGB: "Augsburg",
    AGC: "Pittsburgh",
    AGF: "Agen/La Garenne",
    AGH: "Ã„ngelholm",
    AGP: "MÃ¡laga",
    AGR: "Agra",
    AGS: "Augusta",
    AGT: "Ciudad del Este",
    AGU: "Aguascalientes",
    AGV: "Acarigua",
    AGX: "Agatti",
    AGZ: "Aggeneys",
    AHB: "Abha",
    AHE: "Ahe Atoll",
    AHJ: "Aba",
    AHN: "Athens",
    AHO: "Alghero",
    AHU: "Al Hoceima",
    AIN: "Wainwright",
    AJA: "Ajaccio/NapolÃ©on Bonaparte",
    AJF: "Al-Jawf",
    AJI: "AÄŸrÄ±",
    AJL: "Aizawl (Lengpui)",
    AJN: "Ouani",
    AJR: "Arvidsjaur",
    AJU: "Aracaju",
    AJY: "Agadez",
    AKC: "Akron",
    AKD: "Akola",
    AKF: "Kufra",
    AKH: null,
    AKJ: "Asahikawa",
    AKL: "Auckland",
    AKN: "King Salmon",
    AKP: "Anaktuvuk Pass",
    AKR: "Akure",
    AKT: "Akrotiri",
    AKU: "Aksu (Onsu)",
    AKV: "Akulivik",
    AKW: "Aghajari",
    AKX: "Aktobe",
    AKY: "Sittwe",
    ALA: "Almaty",
    ALB: "Albany",
    ALC: "Alicante",
    ALF: "Alta",
    ALG: "Algiers",
    ALH: "Albany",
    ALI: "Alice",
    ALJ: "Alexander Bay",
    ALL: "Albenga (SV)",
    ALM: "Alamogordo",
    ALN: "Alton/St Louis",
    ALO: "Waterloo",
    ALP: "Aleppo",
    ALR: "Alexandra",
    ALS: "Alamosa",
    ALW: "Walla Walla",
    AMA: "Amarillo",
    AMD: "Ahmedabad",
    AMH: null,
    AMM: "Amman",
    AMQ: "Ambon",
    AMS: "Amsterdam",
    AMV: "Amderma",
    AMZ: "Manurewa",
    ANB: "Anniston",
    ANC: "Anchorage",
    AND: "Anderson",
    ANE: "Angers/MarcÃ©",
    ANF: "Antofagasta",
    ANG: "AngoulÃªme/Brie/Champniers",
    ANI: "Aniak",
    ANK: "Ankara",
    ANM: "Antsirabe",
    ANN: "Metlakatla",
    ANR: "Antwerp",
    ANU: "St. John's",
    ANV: "Anvik",
    ANX: "Andenes",
    AOC: "Altenburg",
    AOE: "EskiÅŸehir",
    AOG: "Anshan",
    AOI: "Ancona",
    AOJ: "Aomori",
    AOK: "Karpathos Island",
    AOL: "Paso de los Libres",
    AOO: "Altoona",
    AOR: "Alor Satar",
    AOT: "Aosta",
    APA: "Denver",
    APF: "Naples",
    APG: "Aberdeen Proving Grounds(Aberdeen)",
    API: "Apiay",
    APL: "Nampula",
    APN: "Alpena",
    APO: "Carepa",
    APW: "Apia",
    APZ: "Zapala",
    AQA: "Araraquara",
    AQG: "Anqing",
    AQI: "Qaisumah",
    AQJ: "Aqaba",
    AQP: "Arequipa",
    ARA: "New Iberia",
    ARC: "Arctic Village",
    ARE: "Arecibo",
    ARH: "Archangelsk",
    ARI: "Arica",
    ARK: "Arusha",
    ARM: "Armidale",
    ARN: "Stockholm/Arlanda",
    ART: "Watertown",
    ARU: "AraÃ§atuba",
    ARW: "Arad",
    ARX: "Aracati",
    ARY: "Ararat",
    ASA: "Asab",
    ASB: "Ashgabat",
    ASD: null,
    ASE: "Aspen",
    ASF: "Astrakhan",
    ASI: "Cat Hill",
    ASJ: "Amami",
    ASK: "Yamoussoukro",
    ASM: "Asmara",
    ASO: "Asosa",
    ASP: "Alice Springs",
    ASR: "Kayseri",
    AST: "Astoria",
    ASU: "AsunciÃ³n",
    ASV: "Amboseli National Park",
    ASW: "Aswan",
    ATA: "Anta",
    ATC: "Arthur's Town",
    ATF: "Ambato",
    ATG: "Kamra",
    ATH: "Athens",
    ATK: "Atqasuk",
    ATL: "Atlanta",
    ATM: "Altamira",
    ATQ: "Amritsar",
    ATR: "Atar",
    ATY: "Watertown",
    ATZ: "Asyut",
    AUA: "Oranjestad",
    AUC: "Arauca",
    AUF: "Auxerre/Branches",
    AUG: "Augusta",
    AUH: "Abu Dhabi",
    AUQ: "Hiva Oa Island",
    AUR: "Aurillac",
    AUS: "Austin",
    AUW: "Wausau",
    AVA: "Xixiu, Anshun",
    AVB: "Aviano (PN)",
    AVI: "Ciego de Avila",
    AVK: "Arvaikheer",
    AVL: "Asheville",
    AVN: "Avignon/Caumont",
    AVP: "Wilkes-Barre/Scranton",
    AVR: "Vila Franca de Xira",
    AVV: "Lara",
    AWA: "Awasa",
    AWK: "Wake Island",
    AWZ: "Ahvaz",
    AXA: "The Valley",
    AXD: "Alexandroupolis",
    AXF: "Bayanhot",
    AXK: "Ataq",
    AXM: "Armenia",
    AXN: "Alexandria",
    AXP: "Spring Point",
    AXR: null,
    AXT: "Akita",
    AXU: null,
    AYO: "Ayolas",
    AYP: "Ayacucho",
    AYQ: "Ayers Rock",
    AYT: "Antalya",
    AYX: "Atalaya",
    AZA: "Mesa",
    AZD: "Yazd",
    AZI: "Abu Dhabi",
    AZN: "Andizhan",
    AZO: "Kalamazoo",
    AZR: "Adrar",
    AZS: "Samana",
    BAB: "Marysville",
    BAD: "Bossier City",
    BAF: "Westfield/Springfield",
    BAG: "Baguio City",
    BAH: "Manama",
    BAI: "Punta Arenas",
    BAL: "Batman",
    BAQ: "Barranquilla",
    BAR: "Qionghai",
    BAT: "Barretos",
    BAV: "Baotou",
    BAX: "Barnaul",
    BAY: "Baia Mare",
    BBA: "Balmaceda",
    BBD: "Brady",
    BBI: "Bhubaneswar",
    BBK: "Kasane",
    BBM: "Battambang",
    BBN: "Bario",
    BBO: "Berbera",
    BBQ: "Codrington",
    BBS: "Yateley",
    BBT: "BerbÃ©rati",
    BBU: "Bucharest",
    BCA: "Baracoa",
    BCD: "Bacolod City",
    BCE: "Bryce Canyon",
    BCH: "Baucau",
    BCI: "Barcaldine",
    BCL: "Pococi",
    BCM: "BacÄƒu",
    BCN: "Barcelona",
    BCQ: "Brak",
    BCU: "Bauchi",
    BCW: "Benguera Island",
    BDA: "Hamilton",
    BDB: "Bundaberg",
    BDE: "Baudette",
    BDH: "Bandar Lengeh",
    BDL: "Hartford",
    BDM: "BandÄ±rma",
    BDO: "Bandung-Java Island",
    BDQ: "Vadodara",
    BDR: "Bridgeport",
    BDS: "Brindisi",
    BDT: "Gbadolite",
    BDU: "MÃ¥lselv",
    BEB: "Balivanich",
    BED: "Bedford",
    BEF: "Bluefileds",
    BEG: "Belgrade",
    BEJ: "Tanjung Redeb - Borneo Island",
    BEK: "Bareilly",
    BEL: "BelÃ©m",
    BEN: "Benghazi",
    BEP: "Bellary",
    BEQ: "Thetford",
    BER: "Berlin",
    BES: "Brest/Guipavas",
    BET: "Bethel",
    BEU: null,
    BEW: "Beira",
    BEX: "Benson",
    BEY: "Beirut",
    BFD: "Bradford",
    BFF: "Scottsbluff",
    BFH: "Curitiba",
    BFI: "Seattle",
    BFJ: "Bijie",
    BFK: "Aurora",
    BFL: "Bakersfield",
    BFM: "Mobile",
    BFN: "Bloemfontain",
    BFO: "Chiredzi",
    BFP: "Beaver Falls",
    BFS: "Belfast",
    BFU: "Bengbu",
    BFV: null,
    BFX: "Bafoussam",
    BGA: "Bucaramanga",
    BGC: "BraganÃ§a",
    BGF: "Bangui",
    BGI: "Bridgetown",
    BGK: "Big Creek",
    BGM: "Binghamton",
    BGN: "Belaya Gora",
    BGO: "Bergen",
    BGR: "Bangor",
    BGW: "Baghdad",
    BGX: "BagÃ©",
    BGY: "Milan",
    BGZ: "Braga",
    BHB: "Bar Harbor",
    BHD: "Belfast",
    BHE: "Blenheim",
    BHH: null,
    BHI: "Bahia Blanca",
    BHJ: "Bhuj",
    BHK: "Bukhara",
    BHM: "Birmingham",
    BHO: "Bhopal",
    BHQ: "Broken Hill",
    BHS: "Bathurst",
    BHU: "Bhavnagar",
    BHV: "Bahawalpur",
    BHX: "Birmingham",
    BIA: "Bastia/Poretta",
    BIF: "Fort Bliss/El Paso",
    BIG: "Delta Junction Ft Greely",
    BIH: "Bishop",
    BIK: "Biak-Supiori Island",
    BIL: "Billings",
    BIM: "South Bimini",
    BIO: "Bilbao",
    BIQ: "Biarritz/Anglet/Bayonne",
    BIR: "Biratnagar",
    BIS: "Bismarck",
    BIX: "Biloxi",
    BIY: "Bisho",
    BJA: "BÃ©jaÃ¯a",
    BJB: "Bojnord",
    BJC: "Denver",
    BJF: "BÃ¥tsfjord",
    BJI: "Bemidji",
    BJL: "Banjul",
    BJM: "Bujumbura",
    BJO: "Bermejo",
    BJR: "Bahir Dar",
    BJV: "Bodrum",
    BJX: "Silao",
    BJY: "Batajnica",
    BJZ: "Badajoz",
    BKB: "Bikaner",
    BKC: "Buckland",
    BKE: "Baker City",
    BKH: "Kekaha",
    BKI: "Kota Kinabalu",
    BKK: "Bangkok",
    BKL: "Cleveland",
    BKO: "Bamako",
    BKQ: "Blackall",
    BKS: "Bengkulu",
    BKW: "Beckley",
    BKY: null,
    BLA: "Barcelona",
    BLD: "Boulder City",
    BLE: "Borlange",
    BLF: "Bluefield",
    BLH: "Blythe",
    BLI: "Bellingham",
    BLJ: "Batna",
    BLK: "Blackpool",
    BLL: "Billund",
    BLN: null,
    BLQ: "Bologna",
    BLR: "Bangalore",
    BLT: null,
    BLV: "Belleville",
    BLZ: "Blantyre",
    BMA: "Stockholm/Bromma",
    BME: "Broome",
    BMG: "Bloomington",
    BMI: "Bloomington/Normal",
    BMM: "Bitam",
    BMV: "Buon Ma Thuot",
    BMY: "Waala",
    BNA: "Nashville",
    BND: "Bandar Abbas",
    BNE: "Brisbane",
    BNI: "Benin",
    BNK: "Ballina",
    BNN: "BrÃ¸nnÃ¸y",
    BNO: "Burns",
    BNS: "Barinas",
    BNX: "Banja Luka",
    BOB: "Motu Mute",
    BOC: "Isla ColÃ³n",
    BOD: "Bordeaux/MÃ©rignac",
    BOG: "Bogota",
    BOH: "Bournemouth",
    BOI: "Boise",
    BOJ: "Burgas",
    BOM: "Mumbai",
    BON: "Kralendijk, Bonaire",
    BOO: "BodÃ¸",
    BOS: "Boston",
    BOU: "Bourges",
    BOY: "Bobo Dioulasso",
    BPC: "Bamenda",
    BPE: "Qinhuangdao",
    BPG: "Barra do GarÃ§as",
    BPH: null,
    BPI: "Big Piney",
    BPL: "Bole",
    BPM: "Hyderabad",
    BPS: "Porto Seguro",
    BPT: "Beaumont/Port Arthur",
    BPX: "Bangda",
    BPY: "Besalampy",
    BQA: "Baler",
    BQH: "London",
    BQK: "Brunswick",
    BQL: null,
    BQN: "Aguadilla",
    BQS: "Blagoveschensk",
    BQT: "Brest",
    BQU: "Bequia",
    BRC: "San Carlos de Bariloche",
    BRD: "Brainerd",
    BRE: "Bremen",
    BRI: "Bari",
    BRK: null,
    BRL: "Burlington",
    BRM: "Barquisimeto",
    BRN: "Bern",
    BRO: "Brownsville",
    BRQ: "Brno",
    BRR: "Eoligarry",
    BRS: "Bristol",
    BRT: "Wurrumiyanga",
    BRU: "Brussels",
    BRW: "UtqiaÄ¡vik",
    BRX: "Barahona",
    BSD: "Baoshan",
    BSG: "Bata",
    BSJ: null,
    BSK: "Biskra",
    BSL: "BÃ¢le/Mulhouse",
    BSO: "Basco",
    BSR: "Basra",
    BTC: "Batticaloa",
    BTH: "Batam Island",
    BTI: "Barter Island",
    BTJ: "Banda Aceh",
    BTK: "Bratsk",
    BTL: "Battle Creek",
    BTM: "Butte",
    BTR: "Baton Rouge",
    BTS: "Bratislava",
    BTT: "Bettles",
    BTU: "Bintulu",
    BTV: "South Burlington",
    BTZ: "Betong",
    BUA: "Buka Island",
    BUD: "Budapest",
    BUF: "Buffalo",
    BUG: "Benguela",
    BUJ: "Ouled Sidi Brahim",
    BUN: "Buenaventura",
    BUP: null,
    BUQ: "Bulawayo",
    BUR: "Burbank",
    BUS: "Batumi",
    BUX: null,
    BUZ: "Bushehr",
    BVA: "Beauvais",
    BVB: "Boa Vista",
    BVC: "Rabil",
    BVE: "Brive la Gaillarde",
    BVG: "BerlevÃ¥g",
    BVH: "Vilhena",
    BVI: null,
    BVJ: "Bovanenkovo",
    BVY: "Beverly / Danvers",
    BWA: "Siddharthanagar (Bhairahawa)",
    BWE: "Braunschweig",
    BWF: "Barrow-in-Furness",
    BWG: "Bowling Green",
    BWH: "Butterworth",
    BWI: "Baltimore",
    BWK: "Bol",
    BWN: "Bandar Seri Begawan",
    BWO: "Balakovo",
    BWQ: null,
    BWT: "Burnie",
    BWU: "Sydney",
    BXB: "Babo-Papua Island",
    BXE: "Bakel",
    BXH: "Balkhash",
    BXR: "Bam",
    BXU: "Butuan",
    BXY: "Baikonur",
    BYC: "Yacuiba",
    BYH: "Blytheville",
    BYI: "Burley",
    BYJ: "Beja",
    BYK: "BouakÃ©",
    BYM: "Bayamo",
    BYN: "Bayankhongor",
    BYS: "Fort Irwin/Barstow",
    BYU: "Bayreuth",
    BZB: "Bazaruto Island",
    BZC: "Cabo Frio",
    BZD: null,
    BZE: "Belize City",
    BZG: "Bydgoszcz",
    BZI: null,
    BZK: "Bryansk",
    BZL: "Barisal",
    BZN: "Bozeman",
    BZO: "Bolzano",
    BZR: "BÃ©ziers/Vias",
    BZU: null,
    BZV: "Brazzaville",
    BZY: "BÄƒlÈ›i",
    BZZ: "Brize Norton",
    CAB: "Cabinda",
    CAC: "Cascavel",
    CAE: "Columbia",
    CAG: "Cagliari",
    CAH: "Ca Mau City",
    CAI: "Cairo",
    CAJ: "Canaima",
    CAK: "Akron",
    CAL: "Campbeltown",
    CAN: "Guangzhou (Huadu)",
    CAP: "Cap Haitien",
    CAQ: "Caucasia",
    CAR: "Caribou",
    CAT: "Cascais",
    CAW: "Campos Dos Goytacazes",
    CAX: "Carlisle",
    CAY: "Matoury",
    CAZ: null,
    CBB: "Cochabamba",
    CBD: "IAF Camp",
    CBG: "Cambridge",
    CBH: "BÃ©char",
    CBJ: "Cabo Rojo",
    CBL: null,
    CBM: "Columbus",
    CBO: "Cotabato City",
    CBQ: "Calabar",
    CBR: "Canberra",
    CBT: "Catumbela",
    CBV: "Coban",
    CCC: "Cayo Coco",
    CCE: "New Cairo",
    CCF: "Carcassonne/Salvaza",
    CCH: "Chile Chico",
    CCJ: "Calicut",
    CCK: "West Island",
    CCL: null,
    CCM: "CriciÃºma",
    CCP: "Concepcion",
    CCS: "Caracas",
    CCU: "Kolkata",
    CCY: "Charles City",
    CCZ: null,
    CDB: "Cold Bay",
    CDC: "Cedar City",
    CDE: "Chengde",
    CDG: "Paris",
    CDJ: "ConceiÃ§Ã£o do Araguaia",
    CDP: "Kadapa",
    CDR: "Chadron",
    CDS: "Childress",
    CDT: "CastellÃ³n de la Plana",
    CDU: "Cobbitty",
    CDV: "Cordova",
    CEB: "Lapu-Lapu City",
    CEC: "Crescent City",
    CED: null,
    CEE: "Cherepovets",
    CEF: "Springfield/Chicopee",
    CEG: "Hawarden",
    CEI: "Chiang Rai",
    CEK: "Chelyabinsk",
    CEN: "Ciudad ObregÃ³n",
    CEQ: "Cannes",
    CER: "Cherbourg/Maupertus",
    CET: "Cholet/Le Pontreau",
    CEW: "Crestview",
    CFE: "Clermont-Ferrand/Auvergne",
    CFG: "Cienfuegos",
    CFK: "Chlef",
    CFN: "Donegal",
    CFR: "Caen/Carpiquet",
    CFS: "Coffs Harbour",
    CFU: "Kerkyra Island",
    CGB: "CuiabÃ¡",
    CGD: "Changde",
    CGF: "Cleveland",
    CGH: "SÃ£o Paulo",
    CGI: "Cape Girardeau",
    CGJ: "Chingola",
    CGK: "Jakarta",
    CGM: "Mambajao",
    CGN: "Cologne",
    CGO: "Zhengzhou",
    CGP: "Chattogram (Chittagong)",
    CGQ: "Changchun",
    CGR: "Campo Grande",
    CGY: "Cagayan de Oro",
    CHA: "Chattanooga",
    CHC: "Christchurch",
    CHG: "Shuangta, Chaoyang",
    CHH: "Chachapoyas",
    CHM: "Chimbote",
    CHO: "Charlottesville",
    CHQ: "Souda",
    CHR: "ChÃ¢teauroux/DÃ©ols",
    CHS: "Charleston",
    CHT: "Te One",
    CHX: "Changuinola",
    CIA: "Rome",
    CID: "Cedar Rapids",
    CIF: "Chifeng",
    CIJ: "Cobija",
    CIS: "Abariringa",
    CIT: "Shymkent",
    CIU: "Sault Ste Marie",
    CIW: "Canouan",
    CIX: "Chiclayo",
    CIY: "Comiso",
    CJA: "Cajamarca",
    CJB: "Coimbatore",
    CJC: "Calama",
    CJJ: "Cheongju",
    CJL: "Chitral",
    CJM: null,
    CJS: "Ciudad JuÃ¡rez",
    CJU: "Jeju City",
    CKB: "Clarksburg",
    CKC: "Cherkasy",
    CKG: "Chongqing",
    CKH: "Chokurdah",
    CKL: "Moscow",
    CKS: "Parauapebas",
    CKT: "Sarakhs",
    CKY: "Conakry",
    CKZ: "Ã‡anakkale",
    CLD: "Carlsbad",
    CLE: "Cleveland",
    CLJ: "Cluj-Napoca",
    CLL: "College Station",
    CLM: "Port Angeles",
    CLN: "Carolina",
    CLO: "Cali",
    CLQ: "Colima",
    CLT: "Charlotte",
    CLU: "Columbus",
    CLY: "Calvi/Sainte-Catherine",
    CLZ: "Guarico",
    CMA: null,
    CMB: "Colombo",
    CMD: null,
    CME: "Ciudad del Carmen",
    CMF: "ChambÃ©ry/Aix-les-Bains",
    CMG: "CorumbÃ¡",
    CMH: "Columbus",
    CMI: "Savoy",
    CMN: "Casablanca",
    CMQ: null,
    CMR: "Colmar/Houssen",
    CMU: "Kundiawa",
    CMW: "Camaguey",
    CMX: "Hancock",
    CNB: null,
    CND: "ConstanÅ£a",
    CNF: "Belo Horizonte",
    CNG: "Cognac/ChÃ¢teaubernard",
    CNI: "Changhai, Dalian",
    CNJ: "Cloncurry",
    CNL: "Sindal",
    CNM: "Carlsbad",
    CNN: "Kannur",
    CNQ: "Corrientes",
    CNR: "ChaÃ±aral",
    CNS: "Cairns",
    CNU: "Chanute",
    CNX: "Chiang Mai",
    COC: "Concordia",
    COD: "Cody",
    COE: "Coeur d'Alene",
    COF: "Cocoa Beach",
    COJ: null,
    COK: "Kochi",
    CON: "Concord",
    COO: "Cotonou",
    COQ: null,
    COR: "Cordoba",
    COS: "Colorado Springs",
    COU: "Columbia",
    CPC: "Chapelco/San Martin de los Andes",
    CPD: null,
    CPE: "Campeche",
    CPF: "Hazard",
    CPH: "Copenhagen",
    CPO: "Copiapo",
    CPR: "Casper",
    CPT: "Cape Town",
    CPV: "Campina Grande",
    CQD: "Shahrekord",
    CQF: "Marck",
    CQM: "Ciudad Real",
    CQW: "Wulong",
    CRA: "Craiova",
    CRC: "Cartago",
    CRD: "Comodoro Rivadavia",
    CRE: "North Myrtle Beach",
    CRG: "Jacksonville",
    CRI: "Colonel Hill",
    CRK: "Mabalacat",
    CRL: "Brussels",
    CRM: "Catarman",
    CRP: "Corpus Christi",
    CRQ: "Caravelas",
    CRV: "Crotone",
    CRW: "Charleston",
    CRZ: "Türkmenabat",
    CSB: "CaransebeÅŸ",
    CSF: "Creil",
    CSG: "Columbus",
    CSK: "Cap Skirring",
    CSV: "Crossville",
    CSX: "Changsha",
    CSY: "Cheboksary",
    CTA: "Catania",
    CTB: "Cut Bank",
    CTC: "Catamarca",
    CTD: "ChitrÃ©",
    CTG: "Cartagena",
    CTL: "Charleville",
    CTM: "Chetumal",
    CTN: null,
    CTS: "Sapporo",
    CTT: "Le Castellet",
    CTU: "Chengdu",
    CUA: "ComondÃº",
    CUB: "Columbia",
    CUC: "CÃºcuta",
    CUE: "Cuenca",
    CUF: "Cuneo",
    CUK: "Caye Caulker",
    CUL: "CuliacÃ¡n",
    CUM: null,
    CUN: "CancÃºn",
    CUP: "CarÃºpano",
    CUQ: "Coen",
    CUR: "Willemstad",
    CUT: "Cutral-Co",
    CUU: "Chihuahua",
    CUZ: "Cusco",
    CVC: null,
    CVE: "CoveÃ±as",
    CVG: "Cincinnati / Covington",
    CVJ: "Temixco",
    CVM: "Ciudad Victoria",
    CVO: "Corvallis",
    CVQ: "Carnarvon",
    CVS: "Clovis",
    CVT: "Coventry",
    CWA: "Mosinee",
    CWB: "Curitiba",
    CWC: "Chernivtsi",
    CWJ: "Cangyuan Va Autonomous County",
    CWL: "Cardiff",
    CWT: null,
    CWW: null,
    CXA: null,
    CXB: "Cox's Bazar",
    CXI: "Banana",
    CXJ: "Caxias Do Sul",
    CXO: "Houston",
    CXP: "Cilacap-Java Island",
    CXR: "Cam Ranh",
    CYA: "Les Cayes",
    CYB: "Cayman Brac",
    CYC: "Caye Chapel",
    CYG: null,
    CYI: "Chiayi City",
    CYO: "Cayo Largo del Sur",
    CYP: "Calbayog City",
    CYS: "Cheyenne",
    CYW: "Celaya",
    CYX: "Cherskiy",
    CYZ: "Cauayan City",
    CZA: "Chichen Itza",
    CZE: "Coro",
    CZF: "Cape Romanzof",
    CZH: "Corozal",
    CZL: "Constantine",
    CZM: "Cozumel",
    CZS: "Cruzeiro Do Sul",
    CZU: "Corozal",
    DAA: "Fort Belvoir",
    DAB: "Daytona Beach",
    DAC: "Dhaka",
    DAD: "Da Nang",
    DAG: "Daggett",
    DAL: "Dallas",
    DAM: "Damascus",
    DAN: "Danville",
    DAR: "Dar es Salaam",
    DAU: "Daru",
    DAV: "David",
    DAY: "Dayton",
    DBB: "El Alamein",
    DBC: "Baicheng",
    DBD: null,
    DBO: "Dubbo",
    DBQ: "Dubuque",
    DBV: "Dubrovnik",
    DCA: "Washington",
    DCF: "Canefield",
    DCI: "Decimomannu",
    DCM: "Castres/Mazamet",
    DCN: "Derby",
    DCT: null,
    DCY: "Daocheng County",
    DDC: "Dodge City",
    DDG: "Zhenxing, Dandong",
    DEA: "Dera Ghazi Khan",
    DEB: "Debrecen",
    DEC: "Decatur",
    DED: "Dehradun",
    DEF: "Dezful",
    DEL: "New Delhi",
    DEN: "Denver",
    DET: "Detroit",
    DEZ: "Deir ez-Zor",
    DFW: "Dallas-Fort Worth",
    DGA: "Dangriga",
    DGE: "Mudgee",
    DGO: "Durango",
    DGP: "Daugavpils",
    DGT: "Dumaguete City",
    DHA: "Dhahran",
    DHF: null,
    DHM: "Gaggal",
    DHN: "Dothan",
    DHR: "Den Helder",
    DHT: "Dalhart",
    DIA: "Doha",
    DIB: "Dibrugarh",
    DIE: "Antisiranana",
    DIG: "Shangri-La",
    DIJ: "Dijon/Longvic",
    DIK: "Dickinson",
    DIL: "Dili",
    DIN: "Dien Bien Phu",
    DIR: "Dire Dawa",
    DIS: "Dolisie",
    DIY: "DiyarbakÄ±r",
    DJE: "Djerba",
    DJG: "Djanet",
    DJJ: "Jayapura-Papua Island",
    DJO: null,
    DKR: "Dakar",
    DKS: "Dikson",
    DLA: "Douala",
    DLC: "Ganjingzi, Dalian",
    DLE: "Dole/Tavaux",
    DLF: "Del Rio",
    DLG: "Dillingham",
    DLH: "Duluth",
    DLI: "Da Lat",
    DLM: "Dalaman",
    DLS: "Dallesport / The Dalles",
    DLU: "Dali (Xiaguan)",
    DLZ: "Dalanzadgad",
    DMA: "Tucson",
    DMB: "Taraz",
    DME: "Moscow",
    DMK: "Bangkok",
    DMM: "Ad Dammam",
    DMN: "Deming",
    DMU: "Dimapur",
    DNA: null,
    DND: "Dundee",
    DNH: "Dunhuang",
    DNK: "Dnipropetrovsk",
    DNL: "Augusta",
    DNQ: "Deniliquin",
    DNR: "Dinard/Pleurtuit/Saint-Malo",
    DNZ: "Denizli",
    DOD: "Dodoma",
    DOG: "Dongola",
    DOH: "Doha",
    DOL: "Deauville",
    DOM: "Marigot",
    DOV: "Dover",
    DOY: "Dongying",
    DPA: "Chicago/West Chicago",
    DPL: "Dipolog City",
    DPO: "Devonport",
    DPS: "Denpasar-Bali Island",
    DQM: "Duqm",
    DRA: "Mercury",
    DRB: "Derby",
    DRG: "Deering",
    DRI: "DeRidder",
    DRN: null,
    DRS: "Dresden",
    DRT: "Del Rio",
    DRW: "Darwin",
    DSA: "Doncaster",
    DSK: "Dera Ismael Khan",
    DSM: "Des Moines",
    DSN: "Ordos",
    DSS: "Dakar",
    DTE: "Daet",
    DTM: "Dortmund",
    DTU: "Heihe",
    DTW: "Detroit",
    DUB: "Dublin",
    DUD: "Dunedin",
    DUE: "Chitato",
    DUG: "Douglas Bisbee",
    DUJ: "Dubois",
    DUM: "Dumai",
    DUR: "Durban",
    DUS: "Düsseldorf",
    DUT: "Unalaska",
    DVO: "Davao",
    DWA: "Dwangwa",
    DWC: "Jebel Ali",
    DWD: "Dawadmi",
    DXB: "Dubai",
    DYA: null,
    DYR: "Anadyr",
    DYS: "Abilene",
    DYU: "Dushanbe",
    DZA: "Dzaoudzi",
    DZN: "Zhezkazgan",
    DZO: "Durazno",
    EAM: "Najran",
    EAR: "Kearney",
    EAS: "Hondarribia",
    EAT: "Wenatchee",
    EAU: "Eau Claire",
    EBA: "Marina Di Campo",
    EBB: "Kampala",
    EBD: "Al-Ubayyid",
    EBG: "El Bagre",
    EBJ: "Esbjerg",
    EBL: "Arbil",
    EBM: "El Borma",
    EBU: "Saint-Ã‰tienne/BouthÃ©on",
    ECG: "Elizabeth City",
    ECH: null,
    ECN: "Nicosia",
    ECP: "Panama City Beach",
    ECV: "Madrid",
    EDF: "Anchorage",
    EDI: "Edinburgh",
    EDL: "Eldoret",
    EDM: "La Roche-sur-Yon/Les Ajoncs",
    EDO: "Edremit",
    EDW: "Edwards",
    EEA: "Correia Pinto",
    EED: "Needles",
    EEN: "Keene",
    EES: "Berenice Troglodytica",
    EFD: "Houston",
    EFL: "Kefallinia Island",
    EGC: "Bergerac/RoumaniÃ¨re",
    EGE: "Eagle",
    EGH: "El Gora",
    EGI: "Crestview",
    EGO: "Belgorod",
    EGS: "EgilsstaÃ°ir",
    EGX: "Egegik",
    EHL: "El Bolson",
    EHM: "Cape Newenham",
    EIB: "Eisenach",
    EIE: "Yeniseysk",
    EIK: "Yeysk",
    EIL: "Fairbanks",
    EIN: "Eindhoven",
    EIS: "Road Town",
    EJA: "Barrancabermeja",
    EJH: "Al Wajh",
    EKA: "Eureka",
    EKB: "Ekibastuz",
    EKN: "Elkins",
    EKO: "Elko",
    EKT: "Eskilstuna",
    ELB: "El Banco",
    ELC: "Elcho Island",
    ELD: "El Dorado",
    ELF: "El Fasher",
    ELG: "El Menia",
    ELH: "North Eleuthera",
    ELM: "Elmira/Corning",
    ELP: "El Paso",
    ELQ: null,
    ELS: "East London",
    ELU: "Guemar",
    ELY: "Ely",
    EMA: "Nottingham",
    EMD: "Emerald",
    EMK: "Emmonak",
    EML: null,
    ENA: "Kenai",
    ENC: "Nancy/Essey",
    END: "Enid",
    ENF: "Enontekio",
    ENK: "Enniskillen",
    ENN: "Nenana",
    ENS: "Enschede",
    ENU: "Enegu",
    ENV: "Wendover",
    ENW: "Kenosha",
    ENY: "Yan'an",
    EOH: "Medellin",
    EOI: "Eday",
    EOR: "Bolivar",
    EOZ: null,
    EPA: "El Palomar",
    EPL: "Ã‰pinal/Mirecourt",
    EPR: "Esperance",
    EPU: "Pärnu",
    EQS: "Esquel",
    ERC: "Erzincan",
    ERF: "Erfurt",
    ERH: "Errachidia",
    ERI: "Erie",
    ERL: "Erenhot",
    ERS: "Windhoek",
    ERZ: "Erzurum",
    ESB: "Ankara",
    ESF: "Alexandria",
    ESG: "Mariscal Estigarribia",
    ESH: "Brighton",
    ESK: null,
    ESL: "Elista",
    ESR: "El Salvador",
    ESU: "Essaouira",
    ETM: "Eilat",
    ETR: "Santa Rosa",
    ETZ: "Metz / Nancy",
    EUG: "Eugene",
    EUN: "El AaiÃºn",
    EUQ: "San Jose",
    EUX: "Sint Eustatius",
    EVE: "Evenes",
    EVG: "Sveg",
    EVN: "Yerevan",
    EVV: "Evansville",
    EVW: "Evanston",
    EVX: "Ã‰vreux/Fauville",
    EWB: "New Bedford",
    EWN: "New Bern",
    EWR: "New York",
    EXT: "Exeter",
    EYK: null,
    EYP: "El Yopal",
    EYW: "Key West",
    EZE: "Buenos Aires (Ezeiza)",
    EZS: "ElazÄ±ÄŸ",
    EZV: null,
    FAB: "Farnborough",
    FAE: "VÃ¡gar",
    FAF: "Fort Eustis",
    FAI: "Fairbanks",
    FAO: "Faro",
    FAR: "Fargo",
    FAT: "Fresno",
    FAV: null,
    FAY: "Fayetteville",
    FAZ: "Fasa",
    FBG: "Fort Bragg",
    FBK: "Fairbanks/Ft Wainwright",
    FBM: "Lubumbashi",
    FCA: "Kalispell",
    FCB: "Ficksburg",
    FCN: "Cuxhaven",
    FCO: "Rome",
    FCS: "Fort Carson",
    FDF: "Fort-de-France",
    FDH: "Friedrichshafen",
    FDU: "Bandundu",
    FDY: "Findlay",
    FEG: "Fergana",
    FEN: "Fernando de Noronha",
    FEZ: "Fes",
    FFD: "Fairford",
    FFO: "Dayton",
    FGU: "Fangatau",
    FHU: "Fort Huachuca / Sierra Vista",
    FIH: "Kinshasa",
    FIZ: null,
    FJR: null,
    FKB: "Baden-Baden",
    FKI: "Kisangani",
    FKJ: null,
    FKL: "Franklin",
    FKQ: "Fakfak-Papua Island",
    FKS: "Sukagawa",
    FLA: "Florencia",
    FLG: "Flagstaff",
    FLL: "Fort Lauderdale",
    FLN: "FlorianÃ³polis",
    FLO: "Florence",
    FLR: "Firenze",
    FLW: "Santa Cruz das Flores",
    FLZ: "Sibolga (Pinangsori)",
    FMA: "Formosa",
    FME: "Fort Meade(Odenton)",
    FMI: null,
    FMM: "Memmingen",
    FMN: "Farmington",
    FMO: "Münster",
    FMY: "Fort Myers",
    FNA: "Freetown (Lungi-Town)",
    FNB: "Neubrandenburg",
    FNC: "Funchal",
    FNI: "NÃ®mes/Garons",
    FNJ: "Pyongyang",
    FNT: "Flint",
    FOC: "Fuzhou",
    FOD: "Fort Dodge",
    FOE: "Topeka",
    FOG: "Foggia",
    FOM: "Foumban",
    FOR: "Fortaleza",
    FOS: null,
    FPO: "Freeport",
    FPR: "Fort Pierce",
    FRA: "Frankfurt am Main",
    FRB: "Forbes",
    FRG: "Farmingdale",
    FRI: "Fort Riley (Junction City)",
    FRL: "ForlÃ¬ (FC)",
    FRO: "FlorÃ¸",
    FRS: "San Benito",
    FRU: "Bishkek",
    FRW: "Francistown",
    FRZ: "Fritzlar",
    FSC: "Figari Sud-Corse",
    FSD: "Sioux Falls",
    FSI: "Fort Sill",
    FSM: "Fort Smith",
    FSP: "Saint-Pierre",
    FSS: "Kinloss",
    FST: "Fort Stockton",
    FSZ: "Makinohara / Shimada",
    FTE: "El Calafate",
    FTI: "Fitiuta Village",
    FTK: "Fort Knox",
    FTU: "TÃ´lanaro",
    FTW: "Fort Worth",
    FTX: "Owando",
    FTY: "Atlanta",
    FUE: "Fuerteventura Island",
    FUG: "Yingzhou, Fuyang",
    FUJ: "Goto",
    FUK: "Fukuoka",
    FUN: "Funafuti",
    FUO: "Foshan (Nanhai)",
    FUT: "Futuna Island",
    FWA: "Fort Wayne",
    FWH: "Fort Worth",
    FXE: "Fort Lauderdale",
    FYJ: "Fuyuan",
    FYN: "Fuyun",
    FYT: null,
    FYU: "Fort Yukon",
    FYV: "Fayetteville",
    GAE: "GabÃ¨s",
    GAF: "Gafsa",
    GAJ: "Higashine",
    GAL: "Galena",
    GAM: "Gambell",
    GAN: "Gan",
    GAO: "GuantÃ¡namo",
    GAQ: null,
    GAU: "Guwahati",
    GAY: null,
    GBB: "Gabala",
    GBE: "Gaborone",
    GBJ: "Grand Bourg",
    GBT: "Gorgan",
    GCC: "Gillette",
    GCH: "Gachsaran",
    GCI: "Saint Peter Port",
    GCJ: "Midrand",
    GCK: "Garden City",
    GCM: "Georgetown",
    GCN: "Grand Canyon - Tusayan",
    GDE: "Gode",
    GDL: "Guadalajara",
    GDN: "GdaÅ„sk",
    GDO: null,
    GDQ: "Gondar",
    GDT: "Cockburn Town",
    GDV: "Glendive",
    GDX: "Magadan",
    GDZ: "Gelendzhik",
    GEA: "NoumÃ©a",
    GEC: "GeÃ§itkale",
    GEG: "Spokane",
    GEL: "Santo Ã‚ngelo",
    GEO: "Georgetown",
    GER: "Nueva Gerona",
    GES: "General Santos",
    GET: "Geraldton",
    GEV: "Gällivare",
    GFF: "Griffith",
    GFK: "Grand Forks",
    GFL: "Glens Falls",
    GFN: null,
    GFR: "Granville",
    GFY: "Grootfontein",
    GGG: "Longview",
    GGT: "Moss Town",
    GGW: "Glasgow",
    GHA: "GhardaÃ¯a",
    GHB: "Governor's Harbour",
    GHC: "Bullocks Harbour",
    GHT: "Ghat",
    GHU: "Gualeguaychu",
    GIB: "Gibraltar",
    GIG: "Rio De Janeiro",
    GIL: "Gilgit",
    GIR: "Girardot",
    GIS: "Gisborne",
    GIZ: "Jizan",
    GJA: "Guanaja",
    GJL: "Jijel",
    GJM: "GuajarÃ¡-Mirim",
    GJT: "Grand Junction",
    GKA: "Goronka",
    GKE: null,
    GKN: "Gulkana",
    GLA: "Paisley, Renfrewshire",
    GLD: "Goodland",
    GLF: "Golfito",
    GLH: "Greenville",
    GLI: null,
    GLO: "Staverton",
    GLS: "Galveston",
    GLT: "Gladstone",
    GLU: "Gelephu",
    GLZ: "Breda",
    GMA: "Gemena",
    GMB: "Gambela",
    GME: "Gomel",
    GML: "Kiev",
    GMO: "Gombe",
    GMP: "Seoul",
    GMQ: "Golog",
    GMR: null,
    GMU: "Greenville",
    GNA: "Hrodna",
    GNB: "Saint-Ã‰tienne-de-Saint-Geoirs",
    GND: "Saint George's",
    GNS: "Gunungsitoli",
    GNV: "Gainesville",
    GNY: "ÅžanlÄ±urfa",
    GOA: "Genova",
    GOH: "Nuuk",
    GOI: "Vasco da Gama",
    GOJ: "Nizhny Novgorod",
    GOM: "Goma",
    GON: "Groton (New London)",
    GOP: "Gorakhpur",
    GOQ: "Golmud",
    GOT: "Gothenburg",
    GOU: "Garoua",
    GOV: "Nhulunbuy",
    GOZ: "Gorna Oryahovitsa",
    GPA: "Patras",
    GPI: "Guapi",
    GPL: "Pococi",
    GPN: null,
    GPO: "General Pico",
    GPT: "Gulfport",
    GRB: "Green Bay",
    GRF: "Fort Lewis/Tacoma",
    GRI: "Grand Island",
    GRJ: "George",
    GRK: "Killeen",
    GRO: "Girona",
    GRQ: "Groningen",
    GRR: "Grand Rapids",
    GRS: "Grosetto",
    GRU: "SÃ£o Paulo",
    GRV: "Grozny",
    GRW: "Santa Cruz da Graciosa",
    GRX: "Granada",
    GRZ: "Graz (Feldkirchen bei Graz)",
    GSB: "Goldsboro",
    GSE: "Gothenburg",
    GSJ: "Puerto San JosÃ©",
    GSO: "Greensboro",
    GSP: "Greer",
    GST: "Gustavus",
    GSV: "Saratov",
    GTE: "Groote Eylandt",
    GTF: "Great Falls",
    GTN: "Glentanner Station",
    GTR: "Columbus/W Point/Starkville",
    GUA: "Guatemala City",
    GUH: null,
    GUI: null,
    GUJ: "GuaratinguetÃ¡",
    GUL: null,
    GUM: "HagÃ¥tÃ±a, Guam International Airport",
    GUP: "Gallup",
    GUQ: "Guanare",
    GUR: "Gurney",
    GUS: "Peru",
    GUW: "Atyrau",
    GUY: "Guymon",
    GVA: "Geneva",
    GVN: "Sovetskaya Gavan",
    GVX: "Gävle / Sandviken",
    GWD: "Gwadar",
    GWE: "Gweru",
    GWL: "Gwalior",
    GWO: "Greenwood",
    GWT: "Westerland",
    GWY: "Galway",
    GXF: "Seiyun",
    GXG: "Negage",
    GXH: "Xiahe",
    GXQ: "Coyhaique",
    GYD: "Baku",
    GYE: "Guayaquil",
    GYG: "Magan",
    GYI: "Gisenyi",
    GYM: "Guaymas",
    GYN: "GoiÃ¢nia",
    GYS: "Guangyuan",
    GYU: "Guyuan",
    GYY: "Gary",
    GZP: "GazipaÅŸa",
    GZT: "Gaziantep",
    GZW: "Qazvin",
    HAC: "Hachijojima",
    HAD: "Halmstad",
    HAH: "Moroni",
    HAJ: "Hannover",
    HAK: "Haikou (Meilan)",
    HAM: "Hamburg",
    HAN: "Soc Son, Hanoi",
    HAQ: "Haa Dhaalu Atoll",
    HAS: "Ha'il",
    HAU: "KarmÃ¸y",
    HAV: "Havana",
    HAW: "Haverfordwest",
    HBA: "Hobart",
    HBE: "Alexandria",
    HBG: "Hattiesburg",
    HBR: "Hobart",
    HBX: "Hubli",
    HCJ: "Hechi (Jinchengjiang)",
    HCN: "Hengchung",
    HCQ: null,
    HCR: "Holy Cross",
    HCZ: "Chenzhou",
    HDF: "Heringsdorf",
    HDG: "Handan",
    HDM: "Hamadan",
    HDY: "Hat Yai",
    HEA: "Guzara",
    HEH: "Heho",
    HEK: "Heihe",
    HEL: "Helsinki",
    HER: "Heraklion",
    HET: "Hohhot",
    HFA: "Haifa",
    HFD: "Hartford",
    HFE: "Hefei",
    HFN: "Höfn",
    HFS: "RÃ¥da",
    HFT: "Hammerfest",
    HGA: "Hargeisa",
    HGH: "Hangzhou",
    HGN: null,
    HGO: "Korhogo",
    HGR: "Hagerstown",
    HGU: "Mount Hagen",
    HHE: "Hachinohe",
    HHN: "Frankfurt am Main",
    HHQ: "Hua Hin",
    HHR: "Hawthorne",
    HIA: "Huai'an",
    HIB: "Hibbing",
    HID: "Horn Island",
    HIF: "Ogden",
    HII: "Lake Havasu City",
    HIJ: "Hiroshima",
    HIK: "Honolulu",
    HIM: "Polonnaruwa Town",
    HIN: "Sacheon",
    HIO: "Portland",
    HIR: "Honiara",
    HJJ: "Huaihua",
    HJR: "Khajuraho",
    HKD: "Hakodate",
    HKG: "Hong Kong",
    HKK: null,
    HKN: "Kimbe",
    HKT: "Phuket",
    HKY: "Hickory",
    HLA: "Johannesburg",
    HLD: "Hailar",
    HLG: "Wheeling",
    HLN: "Helena",
    HLP: "Jakarta",
    HLR: "Fort Hood",
    HLT: null,
    HLZ: "Hamilton",
    HMA: "Khanty-Mansiysk",
    HMB: "Suhaj",
    HME: "Hassi Messaoud",
    HMI: "Hami",
    HMJ: "Khmelnytskyi",
    HMN: "Alamogordo",
    HMO: "Hermosillo",
    HMV: "Hemavan",
    HNA: "Hanamaki",
    HND: "Tokyo",
    HNL: "Honolulu",
    HNM: "Hana",
    HNS: "Haines",
    HOB: "Hobbs",
    HOD: "Hodeida",
    HOF: "Hofuf",
    HOG: "Holguin",
    HOI: "Otepa",
    HOM: "Homer",
    HON: "Huron",
    HOP: "Fort Campbell/Hopkinsville",
    HOQ: "Hof",
    HOR: "Horta",
    HOT: "Hot Springs",
    HOU: "Houston",
    HOV: "Ã˜rsta",
    HPA: "Lifuka",
    HPB: "Hooper Bay",
    HPG: "Shennongjia",
    HPH: "Haiphong",
    HPN: "White Plains",
    HQM: "Hoquiam",
    HRB: "Harbin",
    HRE: "Harare",
    HRG: "Hurghada",
    HRI: null,
    HRK: "Kharkiv",
    HRL: "Harlingen",
    HRM: "Hassi R'Mel",
    HRO: "Harrison",
    HRS: "Harrismith",
    HRT: "Linton-On-Ouse",
    HSA: null,
    HSC: "Ruyuan Yao Autonomous County (Shaoguan)",
    HSG: "Saga",
    HSL: "Huslia",
    HSM: null,
    HSS: null,
    HST: "Homestead",
    HSV: "Huntsville",
    HSZ: "Hsinchu City",
    HTA: "Chita",
    HTG: "Khatanga",
    HTI: "Hamilton Island",
    HTN: "Hotan",
    HTS: "Huntington",
    HTT: "Mengnai",
    HTU: null,
    HTV: "Huntsville",
    HTY: "Antakya",
    HUA: "Redstone Arsnl Huntsville",
    HUF: "Terre Haute",
    HUH: "Fare",
    HUI: "Huáº¿",
    HUL: "Houlton",
    HUN: "Hualien City",
    HUO: "Holingol",
    HUT: "Hutchinson",
    HUU: "HuÃ¡nuco",
    HUX: "Huatulco",
    HUY: "Grimsby",
    HUZ: "Huizhou (Pingtan)",
    HVA: "Analalava",
    HVB: "Hervey Bay",
    HVD: "Khovd",
    HVG: "HonningsvÃ¥g",
    HVN: "New Haven",
    HVR: "Havre",
    HWN: "Hwange",
    HXX: null,
    HYA: "Hyannis",
    HYD: "Hyderabad",
    HYN: "Huangyan",
    HYR: "Hayward",
    HYS: "Hays",
    HZA: "Heze",
    HZB: "Merville/Calonne",
    HZH: "Liping",
    HZK: "Husavik",
    HZU: "Chengdu",
    IAA: "Igarka",
    IAB: "Wichita",
    IAD: "Washington",
    IAG: "Niagara Falls",
    IAH: "Houston",
    IAM: "In AmÃ©nas",
    IAN: "Kiana",
    IAS: "IaÅŸi",
    IBA: "Ibadan",
    IBE: "IbaguÃ©",
    IBL: "Bazaruto Island",
    IBP: "Iberia",
    IBR: "Omitama",
    IBZ: "Ibiza",
    ICN: "Seoul",
    ICT: "Wichita",
    IDA: "Idaho Falls",
    IDR: "Indore",
    IDY: "ÃŽle d'Yeu",
    IEG: "Babimost",
    IEJ: "Ie",
    IEV: "Kiev",
    IFJ: "Isafjördur",
    IFN: "Isfahan",
    IFO: "Ivano-Frankivsk",
    IFP: "Bullhead City",
    IGA: "Matthew Town",
    IGD: "IÄŸdÄ±r",
    IGL: "KaklÄ±Ã§ Mahallesi",
    IGM: "Kingman",
    IGR: "Puerto Iguazu",
    IGS: "Manching",
    IGT: "Sunzha",
    IGU: "Foz do IguaÃ§u",
    IHR: "Iranshahr",
    IIL: "Ilam",
    IJK: "Izhevsk",
    IKA: "Tehran",
    IKI: "Iki",
    IKK: "Kankakee",
    IKS: "Tiksi",
    IKT: "Irkutsk",
    IKU: "Tamchy",
    ILD: "Lleida",
    ILF: "Ilford",
    ILG: "Wilmington",
    ILI: "Iliamna",
    ILM: "Wilmington",
    ILN: "Wilmington",
    ILO: "Iloilo (Cabatuan)",
    ILP: "ÃŽle des Pins",
    ILQ: "Ilo",
    ILR: "Ilorin",
    ILY: "Port Ellen",
    ILZ: "Å½ilina",
    IMF: "Imphal",
    IMP: "Imperatriz",
    INA: "Inta",
    INC: "Yinchuan",
    IND: "Indianapolis",
    INH: "Inhambane",
    INI: "Nis",
    INK: "Wink",
    INL: "International Falls",
    INN: "Innsbruck",
    INT: "Winston Salem",
    INU: "Yaren District",
    INV: "Inverness",
    INW: "Winslow",
    INZ: "In Salah",
    IOA: "Ioannina",
    IOM: "Castletown",
    IOS: "IlhÃ©us",
    IPC: "Isla De Pascua",
    IPH: "Ipoh",
    IPI: "Ipiales",
    IPL: "Imperial",
    IPN: "Ipatinga",
    IPT: "Williamsport",
    IQA: "HÄ«t",
    IQM: "Qiemo",
    IQN: "Qingyang",
    IQQ: "Iquique",
    IQT: "Iquitos",
    IRD: "Ishurdi",
    IRG: "Lockhart River",
    IRI: "Nduli",
    IRJ: "La Rioja",
    IRK: "Kirksville",
    IRP: null,
    ISA: "Mount Isa",
    ISB: "Islamabad",
    ISE: "Isparta",
    ISG: "Ishigaki",
    ISK: "Nasik",
    ISL: "BakÄ±rköy, Istanbul",
    ISM: "Orlando",
    ISO: "Kinston",
    ISP: "Islip",
    IST: "Arnavutköy, Istanbul",
    ISU: "Sulaymaniyah",
    ITA: "Itacoatiara",
    ITB: "Itaituba",
    ITH: "Ithaca",
    ITM: "Osaka",
    ITO: "Hilo",
    IUE: "Alofi",
    IVC: "Invercargill",
    IVL: "Ivalo",
    IVR: "Inverell",
    IWA: "Ivanovo",
    IWJ: "Masuda",
    IWK: "Iwakuni",
    IWO: "Ogasawara",
    IXA: "Agartala",
    IXB: "Siliguri",
    IXC: "Chandigarh",
    IXD: "Allahabad",
    IXE: "Mangalore",
    IXG: "Belgaum",
    IXH: "Kailashahar",
    IXI: "Lilabari",
    IXJ: "Jammu",
    IXK: "Keshod",
    IXL: "Leh",
    IXM: "Madurai",
    IXP: "Pathankot",
    IXR: "Ranchi",
    IXS: "Silchar",
    IXU: "Aurangabad",
    IXV: null,
    IXW: "Jamshedpur",
    IXX: "Bidar",
    IXY: "Kandla",
    IXZ: "Port Blair",
    IZA: "Juiz de Fora",
    IZO: "Izumo",
    IZT: "Ixtepec",
    JAA: "Jalalabad",
    JAC: "Jackson",
    JAD: "Perth",
    JAE: "JaÃ©n",
    JAF: "Jaffna",
    JAG: "Jacobabad",
    JAI: "Jaipur",
    JAK: "Jacmel",
    JAL: "Xalapa",
    JAM: "Yambol",
    JAN: "Jackson",
    JAU: "Jauja",
    JAX: "Jacksonville",
    JBQ: "La Isabela",
    JBR: "Jonesboro",
    JCR: "Jacareacanga",
    JCT: "Junction",
    JDF: "Juiz de Fora",
    JDG: "Jeju Island",
    JDH: "Jodhpur",
    JDZ: "Jingdezhen",
    JED: "Jeddah",
    JEE: "Jeremie",
    JEG: "Aasiaat",
    JER: "Saint Helier",
    JFK: "New York / JFK",
    JFN: "Ashtabula",
    JGA: "Jamnagar",
    JGD: "Jagdaqi",
    JGS: "Ji'an",
    JHB: "Johor Bahru",
    JHF: "SÃ£o Roque",
    JHG: "Jinghong (Gasa)",
    JHM: "Lahaina",
    JHS: "Sisimiut",
    JHW: "Jamestown",
    JIB: "Djibouti City",
    JIJ: "Jijiga",
    JIM: "Jimma",
    JIQ: "Qianjiang",
    JJD: "Cruz",
    JJI: "Juanjui",
    JJN: "Quanzhou",
    JKG: "Jönköping",
    JKH: "Chios Island",
    JKR: "Janakpur",
    JLN: "Joplin",
    JLR: null,
    JMJ: "Lancang Lahu Autonomous County",
    JMK: "Mykonos Island",
    JMS: "Jamestown",
    JMU: "Jiamusi",
    JNB: "Johannesburg",
    JNG: "Jining",
    JNU: "Juneau",
    JNZ: "Linghai, Jinzhou",
    JOE: "Joensuu / Liperi",
    JOG: "Yogyakarta-Java Island",
    JOH: "Port St Johns",
    JOI: "Joinville",
    JOK: "Yoshkar-Ola",
    JOL: null,
    JOS: "Jos",
    JPA: "JoÃ£o Pessoa",
    JRF: "Kapolei",
    JRH: "Jorhat",
    JRO: "Arusha",
    JSA: null,
    JSH: "Crete Island",
    JSI: "Skiathos",
    JSJ: "Jiansanjiang",
    JSR: "Jashore (Jessore)",
    JST: "Johnstown",
    JTC: "Bauru",
    JTR: "Santorini Island",
    JUB: "Juba",
    JUJ: "San Salvador de Jujuy",
    JUL: "Juliaca",
    JUZ: "Quzhou",
    JWA: "Jwaneng",
    JWN: "Zanjan",
    JXA: "Jixi",
    JXN: "Jackson",
    JYR: "Jiroft",
    JYV: "Jyväskylän Maalaiskunta",
    JZH: "Jiuzhaigou",
    KAB: "Kariba",
    KAC: "Qamishly",
    KAD: "Kaduna",
    KAG: "Gangneung",
    KAI: "Kaieteur Falls",
    KAJ: "Kajaani",
    KAN: "Kano",
    KAO: "Kuusamo",
    KAT: "Kaitaia",
    KAU: "Kauhava",
    KAW: "Kawthoung",
    KBK: "Kushinagar",
    KBL: "Kabul",
    KBP: "Kiev",
    KBR: "Kota Baharu",
    KBS: "Bo",
    KBV: "Krabi",
    KCH: "Kuching",
    KCM: "KahramanmaraÅŸ",
    KCO: "Kartepe",
    KCT: "Galle",
    KCZ: "Nankoku",
    KDH: "Khvoshab",
    KDL: "Kärdla",
    KDM: "Huvadhu Atoll",
    KDO: "Kadhdhoo",
    KDT: "Nakhon Pathom",
    KDU: "Skardu",
    KEF: "Reykjavik",
    KEJ: "Kemerovo",
    KEL: "Kiel",
    KEM: "Kemi / Tornio",
    KEN: "Kenema",
    KEP: "Nepalgunj",
    KER: "Kerman",
    KES: "Kelsey",
    KET: "Kengtung",
    KEV: "Jämsä",
    KFS: "Kastamonu",
    KFZ: "KukÃ«s",
    KGA: "Kananga",
    KGC: null,
    KGD: "Kaliningrad",
    KGF: "Karaganda",
    KGG: "KÃ©dougou",
    KGI: "Kalgoorlie",
    KGJ: "Karonga",
    KGL: "Kigali",
    KGP: "Kogalym",
    KGS: "Kos Island",
    KGT: "Kangding",
    KGY: null,
    KHD: null,
    KHE: "Kherson",
    KHG: "Kashgar",
    KHH: "Kaohsiung (Xiaogang)",
    KHI: "Karachi",
    KHJ: null,
    KHK: "Khark",
    KHN: "Nanchang",
    KHS: "Khasab",
    KHT: "Khost",
    KHV: "Khabarovsk",
    KID: "Kristianstad",
    KIH: "Kish Island",
    KIJ: "Niigata",
    KIK: "Kirkuk",
    KIM: "Kimberley",
    KIN: "Kingston",
    KIR: "Killarney",
    KIS: "Kisumu",
    KIV: "ChiÅŸinÄƒu",
    KIW: "Kitwe",
    KIX: "Osaka",
    KJA: "Krasnoyarsk",
    KJB: "Orvakal",
    KJH: "Huangping",
    KJI: "Burqin",
    KJK: "Wevelgem",
    KJT: "Kertajati",
    KKC: "Khon Kaen",
    KKE: "Kerikeri",
    KKJ: "Kitakyushu",
    KKN: "Kirkenes",
    KKR: "Raitahiti",
    KKS: "Kashan",
    KKW: "Kikwit",
    KKX: "Kikai",
    KLC: "Kaolack",
    KLD: "Tver",
    KLF: "Kaluga",
    KLH: null,
    KLO: "Kalibo",
    KLR: "Kalmar",
    KLS: "Kelso",
    KLU: "Klagenfurt am Wörthersee",
    KLV: "Karlovy Vary",
    KLW: "Klawock",
    KLX: "Kalamata",
    KLZ: "Kleinsee",
    KMA: "Kerema",
    KMC: "King Khaled Military City",
    KME: "Kamembe",
    KMG: "Kunming",
    KMH: "Kuruman",
    KMI: "Miyazaki",
    KMJ: "Kumamoto",
    KMN: null,
    KMP: "Keetmanshoop",
    KMQ: "Kanazawa",
    KMS: "Kumasi",
    KMU: "Kismayo",
    KMW: "Kostroma",
    KMX: "Khamis Mushait",
    KNA: "ViÃ±a Del Mar",
    KND: "Kindu",
    KNF: "Marham",
    KNG: "Kaimana-Papua Island",
    KNH: "Shang-I",
    KNO: "Bandara Kuala Namu",
    KNQ: "KonÃ©",
    KNR: "Kangan",
    KNS: null,
    KNU: "Kanpur",
    KNX: "Kununurra",
    KOA: "Kailua-Kona",
    KOC: "Koumac",
    KOI: "Orkney Islands",
    KOJ: "Kagoshima",
    KOK: "Kokkola / Kruunupyy",
    KON: "Kontum",
    KOP: null,
    KOU: "Koulamoutou",
    KOV: "Kokshetau",
    KPC: "Port Clarence",
    KPO: "Pohang",
    KPS: null,
    KPW: "Keperveem",
    KQH: "Ajmer (Kishangarh)",
    KQT: "Kurgan-Tyube",
    KRA: null,
    KRF: "Nyland",
    KRK: "KrakÃ³w",
    KRL: "Korla",
    KRN: "Kiruna",
    KRO: "Kurgan",
    KRP: "Karup",
    KRR: "Krasnodar",
    KRS: "Kjevik",
    KRT: "Khartoum",
    KRW: "Turkmenbashi",
    KSA: "Okat",
    KSC: "KoÅ¡ice",
    KSD: "Karlstad",
    KSF: "Kassel",
    KSH: "Kermanshah",
    KSK: null,
    KSL: "Kassala",
    KSM: "St Mary's",
    KSN: "Kostanay",
    KSU: "Kvernberget",
    KSY: "Kars",
    KSZ: "Kotlas",
    KTA: "Karratha",
    KTD: "Kitadaito",
    KTE: "Kerteh",
    KTG: "Ketapang",
    KTL: "Kitale",
    KTM: "Kathmandu",
    KTN: "Ketchikan",
    KTP: "Tinson Pen",
    KTQ: "Kitee",
    KTR: null,
    KTT: "Kittilä",
    KTU: "Kota",
    KTW: "Katowice",
    KUA: "Kuantan",
    KUF: "Samara",
    KUH: "Kushiro",
    KUL: "Kuala Lumpur",
    KUM: "Yakushima",
    KUN: "Kaunas",
    KUO: "Kuopio / Siilinjärvi",
    KUS: "Kulusuk",
    KUT: "Kopitnari",
    KUU: "Bhuntar",
    KUV: "Kunsan",
    KVA: "Kavala",
    KVB: "Skövde",
    KVD: "Ganja",
    KVG: "Kavieng",
    KVL: "Kivalina",
    KVO: "Kraljevo",
    KVX: "Kirov",
    KWA: "Kwajalein",
    KWE: "Guiyang",
    KWG: "Kryvyi Rih",
    KWI: "Kuwait City",
    KWJ: "Gwangju",
    KWL: "Guilin (Lingui)",
    KWM: "Kowanyama",
    KWY: "Kiwayu",
    KWZ: null,
    KXE: "Klerksdorp",
    KXK: "Komsomolsk-on-Amur",
    KYA: "Konya",
    KYD: "Orchid Island",
    KYE: "Tripoli",
    KYP: "Kyaukpyu",
    KYS: null,
    KYZ: "Kyzyl",
    KZC: "Kampong Chhnang",
    KZI: "Kozani",
    KZN: "Kazan",
    LAA: "Lamar",
    LAD: "Luanda",
    LAE: "Lae",
    LAF: "West Lafayette",
    LAI: "Lannion",
    LAJ: "Lages",
    LAK: "Aklavik",
    LAL: "Lakeland",
    LAN: "Lansing",
    LAO: "Laoag City",
    LAP: "La Paz",
    LAQ: "Al Bayda'",
    LAR: "Laramie",
    LAS: "Las Vegas",
    LAU: "Lamu",
    LAW: "Lawton",
    LAX: "Los Angeles",
    LAY: "Ladysmith",
    LAZ: "Bom Jesus da Lapa",
    LBA: "Leeds",
    LBB: "Lubbock",
    LBC: "Lübeck",
    LBD: "Khujand",
    LBE: "Latrobe",
    LBF: "North Platte",
    LBG: "Paris",
    LBI: "Albi/Le SÃ©questre",
    LBL: "Liberal",
    LBQ: "Lambarene",
    LBS: null,
    LBT: "Lumberton",
    LBU: "Labuan",
    LBV: "Libreville",
    LBX: null,
    LBY: "La Baule-Escoublac",
    LCA: "Larnaca",
    LCC: null,
    LCE: "La Ceiba",
    LCG: "Culleredo",
    LCH: "Lake Charles",
    LCJ: "Lodz",
    LCK: "Columbus",
    LCL: "Pinar del Rio",
    LCX: "Longyan",
    LCY: "London",
    LDB: "Londrina",
    LDE: "Tarbes/Lourdes/PyrÃ©nÃ©es",
    LDS: "Yichun",
    LDU: "Lahad Datu",
    LDV: "Landivisiau",
    LDY: "Derry",
    LEA: "Exmouth",
    LEB: "Lebanon",
    LED: "St. Petersburg",
    LEE: "Leesburg",
    LEH: "Le Havre/Octeville",
    LEI: "Almeria",
    LEJ: "Leipzig",
    LEN: "LeÃ³n",
    LER: null,
    LET: "Leticia",
    LEX: "Lexington",
    LEY: "Lelystad",
    LFI: "Hampton",
    LFK: "Lufkin",
    LFM: "Lamerd",
    LFQ: "Linfen",
    LFR: null,
    LFT: "Lafayette",
    LFW: "LomÃ©",
    LGA: "New York",
    LGB: "Long Beach",
    LGG: "LiÃ¨ge",
    LGH: null,
    LGI: "Deadman's Cay",
    LGK: "Langkawi",
    LGP: "Legazpi City",
    LGR: "Cochrane",
    LGS: "Malargue",
    LGU: "Logan",
    LGW: "London",
    LHA: null,
    LHE: "Lahore",
    LHG: null,
    LHK: "Xiangyang",
    LHR: "London",
    LHS: "Las Heras",
    LHW: "Lanzhou",
    LIF: "Lifou",
    LIG: "Limoges/Bellegarde",
    LIH: "Lihue",
    LIL: "Lille/Lesquin",
    LIM: "Lima",
    LIN: "Milan",
    LIO: "Puerto Limon",
    LIP: "Lins",
    LIQ: null,
    LIR: "Liberia",
    LIS: "Lisbon",
    LIT: "Little Rock",
    LIW: "Loikaw",
    LJG: "Lijiang",
    LJN: "Angleton",
    LJU: "Ljubljana",
    LKG: "Lokichoggio",
    LKL: "Lakselv",
    LKN: "Leknes",
    LKO: "Lucknow",
    LKY: "Lake Manyara National Park",
    LKZ: "Lakenheath",
    LLA: "LuleÃ¥",
    LLC: "Lal-lo",
    LLE: "Malelane",
    LLF: "Yongzhou",
    LLV: "Lüliang",
    LLW: "Lilongwe",
    LME: "Le Mans/Arnage",
    LMM: "Los Mochis",
    LMN: "Limbang",
    LMO: "Lossiemouth",
    LMP: "Lampedusa",
    LMQ: null,
    LMR: "Lime Acres",
    LMT: "Klamath Falls",
    LND: "Lander",
    LNJ: "Lincang",
    LNK: "Lincoln",
    LNL: "Longnan",
    LNO: "Leonora",
    LNS: "Lancaster",
    LNX: "Smolensk",
    LNY: "Lanai City",
    LNZ: "Linz",
    LOE: null,
    LOK: "Lodwar",
    LOL: "Lovelock",
    LOO: "Laghouat",
    LOP: "Mataram",
    LOS: "Lagos",
    LOU: "Louisville",
    LOV: null,
    LOZ: "London",
    LPA: "Gran Canaria Island",
    LPB: "La Paz / El Alto",
    LPF: "Liupanshui",
    LPG: "La Plata",
    LPI: "Linköping",
    LPK: "Lipetsk",
    LPL: "Liverpool",
    LPP: "Lappeenranta",
    LPQ: "Luang Phabang",
    LPT: null,
    LPX: "Liepaja",
    LPY: "Le Puy/Loudes",
    LRD: "Laredo",
    LRE: "Longreach",
    LRF: "Jacksonville",
    LRH: "La Rochelle/ÃŽle de RÃ©",
    LRL: "Niamtougou",
    LRM: "La Romana",
    LRR: "Lar",
    LRT: "Lorient/Lann/BihouÃ©",
    LRU: "Las Cruces",
    LSC: "La Serena-Coquimbo",
    LSE: "La Crosse",
    LSF: "Fort Benning(Columbus)",
    LSH: "Lashio",
    LSI: "Lerwick",
    LSL: "Los Chiles",
    LSP: "ParaguanÃ¡",
    LST: "Launceston",
    LSV: "Las Vegas",
    LSX: "Lhok Sukon-Sumatra Island",
    LSY: "Lismore",
    LTA: "Tzaneen",
    LTD: "Ghadames",
    LTI: "Altai",
    LTK: "Latakia",
    LTM: "Lethem",
    LTN: "London",
    LTO: "Loreto",
    LTQ: "Le Touquet-Paris-Plage",
    LTS: "Altus",
    LTU: "Latur",
    LTX: "Latacunga",
    LUD: "Luderitz",
    LUF: "Glendale",
    LUG: "Lugano",
    LUH: null,
    LUK: "Cincinnati",
    LUM: "Mangshi",
    LUN: "Lusaka",
    LUO: "Luena",
    LUQ: "San Luis",
    LUR: "Cape Lisburne",
    LUV: "Langgur",
    LUW: "Luwok",
    LUX: "Luxembourg",
    LUZ: "Lublin",
    LVA: "Laval/Entrammes",
    LVI: "Livingstone",
    LVM: "Livingston",
    LVP: null,
    LVS: "Las Vegas",
    LWB: "Lewisburg",
    LWM: "Lawrence",
    LWN: "Gyumri",
    LWO: "Lviv",
    LWR: "Leeuwarden",
    LWS: "Lewiston",
    LWT: "Lewistown",
    LXA: "Lhasa",
    LXR: "Luxor",
    LYA: "Luoyang",
    LYB: "Little Cayman",
    LYC: "Lycksele",
    LYH: "Lynchburg",
    LYN: "Lyon/Bron",
    LYP: "Faisalabad",
    LYR: "Longyearbyen",
    LYS: "Lyon",
    LYU: "Ely",
    LYX: "Lydd, Ashford",
    LZC: "LÃ¡zaro CÃ¡rdenas",
    LZH: "Liuzhou (Liujiang)",
    LZN: "Matsu (Nangan)",
    LZO: "Yunlong",
    LZY: "Nyingchi",
    MAA: "Chennai",
    MAB: "MarabÃ¡",
    MAD: "Madrid",
    MAF: "Midland",
    MAG: "Madang",
    MAH: "Menorca Island",
    MAI: "Mangochi",
    MAJ: "Majuro Atoll",
    MAK: "Malakal",
    MAM: "Matamoros",
    MAN: "Manchester",
    MAO: "Manaus",
    MAQ: null,
    MAR: "Maracaibo",
    MAS: "Manus Island",
    MAU: null,
    MAX: "Ouro Sogui",
    MAY: "Mangrove Cay",
    MAZ: "Mayaguez",
    MBA: "Mombasa",
    MBD: "Mafeking",
    MBE: "Monbetsu",
    MBG: "Mobridge",
    MBI: "Mbeya",
    MBJ: "Montego Bay",
    MBO: "Mamburao",
    MBS: "Saginaw",
    MBT: "Masbate",
    MBW: "Melbourne",
    MBX: null,
    MCB: "McComb",
    MCC: "Sacramento",
    MCE: "Merced",
    MCF: "Tampa",
    MCG: "McGrath",
    MCI: "Kansas City",
    MCJ: "La Mina-Maicao",
    MCK: "Mc Cook",
    MCN: "Macon",
    MCO: "Orlando",
    MCP: "MacapÃ¡",
    MCS: "Monte Caseros",
    MCT: "Muscat",
    MCU: "MontluÃ§on/GuÃ©ret",
    MCW: "Clear Lake",
    MCX: "Makhachkala",
    MCY: "Maroochydore",
    MCZ: "MaceiÃ³",
    MDC: "Manado",
    MDE: "Medellin",
    MDG: "Mudanjiang",
    MDH: "Carbondale/Murphysboro",
    MDI: "Makurdi",
    MDK: "Mbandaka",
    MDL: "Mandalay",
    MDQ: "Mar del Plata",
    MDT: "Harrisburg",
    MDU: "Mendi",
    MDW: "Chicago",
    MDY: "Sand Island",
    MDZ: "Mendoza",
    MEA: "MacaÃ©",
    MEB: "Essendon Fields",
    MEC: "Manta",
    MED: "Medina",
    MEE: "MarÃ©",
    MEG: "Malanje",
    MEH: "Mehamn",
    MEI: "Meridian",
    MEK: "Meknes",
    MEL: "Melbourne",
    MEM: "Memphis",
    MEN: "Mende/BrÃ©noux",
    MEQ: "Kuala Pesisir",
    MER: "Merced",
    MES: "Medan",
    MEU: "Almeirim",
    MEX: "Mexico City",
    MFD: "Mansfield",
    MFE: "McAllen",
    MFG: "Muzaffarabad",
    MFH: "Mesquite",
    MFK: "Matsu (Beigan)",
    MFM: "Freguesia de Nossa Senhora do Carmo (Taipa)",
    MFQ: "Maradi",
    MFR: "Medford",
    MFU: "Mfuwe",
    MGA: "Managua",
    MGB: "Mount Gambier",
    MGE: "Marietta",
    MGF: "MaringÃ¡",
    MGH: "Margate",
    MGL: "Mönchengladbach",
    MGM: "Montgomery",
    MGN: "MaganguÃ©",
    MGQ: "Mogadishu",
    MGW: "Morgantown",
    MGZ: "Mkeik",
    MHD: "Mashhad",
    MHG: "Mannheim",
    MHH: "Marsh Harbour",
    MHK: "Manhattan",
    MHQ: "Mariehamn",
    MHR: "Sacramento",
    MHT: "Manchester",
    MHU: "Mount Hotham",
    MHZ: "Mildenhall",
    MIA: "Miami",
    MIB: "Minot",
    MID: "MÃ©rida",
    MIE: "Muncie",
    MIG: "Mianyang",
    MII: "Marilia",
    MIK: "Mikkeli",
    MIM: "Merimbula",
    MIP: "Beersheba",
    MIR: "Monastir",
    MIU: "Maiduguri",
    MIV: "Millville",
    MJC: null,
    MJD: "Moenjodaro",
    MJF: "MosjÃ¸en",
    MJI: "Tripoli",
    MJK: "Denham",
    MJL: "Mouila",
    MJM: "Mbuji Mayi",
    MJN: "Mahajanga",
    MJT: "Mytilene",
    MJV: "San Javier",
    MJZ: "Mirny",
    MKC: "Kansas City",
    MKE: "Milwaukee",
    MKG: "Muskegon",
    MKK: "Kaunakakai",
    MKL: "Jackson",
    MKM: "Mukah",
    MKP: "Makemo",
    MKQ: "Merauke",
    MKR: null,
    MKU: "Makokou",
    MKW: "Manokwari-Papua Island",
    MKY: "Mackay",
    MKZ: "Malacca",
    MLA: "Valletta",
    MLB: "Melbourne",
    MLC: "Mc Alester",
    MLE: "MalÃ©",
    MLI: "Moline",
    MLL: "Marshall",
    MLM: "Morelia",
    MLN: "Melilla",
    MLS: "Miles City",
    MLU: "Monroe",
    MLW: "Monrovia",
    MLX: "Malatya",
    MMB: "ÅŒzora",
    MMD: "Minamidaito",
    MME: "Darlington, Durham",
    MMG: null,
    MMJ: "Matsumoto",
    MMK: "Murmansk",
    MMO: "Vila do Maio",
    MMT: "Eastover",
    MMU: "Morristown",
    MMX: "Malmö",
    MMY: "Miyako City",
    MMZ: "Maymana",
    MNG: "Maningrida",
    MNH: "Al Masna'ah",
    MNI: "Gerald's Park",
    MNJ: "Mananjary",
    MNL: "Manila",
    MNR: "Mongu",
    MNX: "ManicorÃ©",
    MOA: "Moa",
    MOB: "Mobile",
    MOC: "Montes Claros",
    MOD: "Modesto",
    MOE: null,
    MOG: "Mong Hsat",
    MOL: "Ã…rÃ¸",
    MON: null,
    MOQ: "Morondava",
    MOT: "Minot",
    MOV: "Moranbah",
    MOZ: "Moorea-Maiao",
    MPH: "Malay",
    MPL: "Montpellier/MÃ©diterranÃ©e",
    MPM: "Maputo",
    MPN: "Mount Pleasant",
    MPV: "Barre/Montpelier",
    MPW: "Mariupol",
    MQC: "Miquelon",
    MQF: "Magnitogorsk",
    MQH: "MinaÃ§u",
    MQJ: "Khonuu",
    MQL: "Mildura",
    MQM: "Mardin",
    MQN: "Mo i Rana",
    MQP: "Mpumalanga",
    MQQ: "Moundou",
    MQS: "Mustique Island",
    MQT: "Gwinn",
    MQU: "Mariquita",
    MQX: null,
    MQY: "Smyrna",
    MRB: "Martinsburg",
    MRD: "MÃ©rida",
    MRE: "Masai Mara",
    MRG: null,
    MRI: "Anchorage",
    MRO: "Masterton",
    MRQ: "Gasan",
    MRR: "MacarÃ¡",
    MRS: "Marseille",
    MRU: "Plaine Magnein",
    MRV: "Mineralnyye Vody",
    MRW: "Lolland Falster / Maribo",
    MRX: "Mahshahr",
    MRY: "Monterey",
    MRZ: "Moree",
    MSA: "Muskrat Dam",
    MSH: "Masirah",
    MSJ: "Misawa",
    MSL: "Muscle Shoals",
    MSN: "Madison",
    MSO: "Missoula",
    MSP: "Minneapolis",
    MSQ: "Minsk",
    MSR: "MuÅŸ",
    MSS: "Massena",
    MST: "Maastricht",
    MSU: "Maseru",
    MSW: "Massawa",
    MSY: "New Orleans",
    MSZ: "MoÃ§Ã¢medes",
    MTC: "Mount Clemens",
    MTH: "Marathon",
    MTJ: "Montrose",
    MTN: "Baltimore",
    MTR: "Monteria",
    MTS: "Manzini",
    MTT: "MinatitlÃ¡n",
    MTY: "Monterrey",
    MTZ: "Masada",
    MUA: "Munda",
    MUB: "Maun",
    MUC: "Munich",
    MUD: "Mueda",
    MUE: "Waimea (Kamuela)",
    MUH: "Marsa Matruh",
    MUI: "Fort Indiantown Gap(Annville)",
    MUN: "Maturin",
    MUO: "Mountain Home",
    MUR: "Marudi",
    MUW: "Ghriss",
    MUX: "Multan",
    MVB: "Franceville",
    MVD: "Montevideo",
    MVF: "MossorÃ³",
    MVP: "MitÃº",
    MVQ: "Mogilev",
    MVR: "Maroua",
    MVT: null,
    MVZ: "Masvingo",
    MWD: "Mianwali",
    MWE: "Merowe",
    MWH: "Moses Lake",
    MWX: "Piseo-ri (Muan)",
    MWZ: "Mwanza",
    MXF: "Montgomery",
    MXI: "Mati",
    MXJ: "Minna",
    MXL: "Mexicali",
    MXM: "Morombe",
    MXN: "Morlaix/Ploujean",
    MXP: "Milan",
    MXV: "Mörön",
    MXX: "Mora",
    MYA: "Moruya",
    MYC: "Maracay",
    MYD: "Malindi",
    MYE: "Miyakejima",
    MYG: "Abrahams Bay",
    MYJ: "Matsuyama",
    MYL: "McCall",
    MYP: "Mary",
    MYR: "Myrtle Beach",
    MYT: "Myitkyina",
    MYU: "Mekoryuk",
    MYV: "Marysville",
    MYW: "Mtwara",
    MYY: "Miri",
    MZB: "Mocimboa da Praia",
    MZG: "Huxi",
    MZI: "SÃ©varÃ©",
    MZL: "Manizales",
    MZO: "Manzanillo",
    MZQ: "Mkuze",
    MZR: "Mazar-i-Sharif",
    MZT: "MazatlÃ¡n",
    MZU: null,
    MZV: "Mulu",
    MZW: "Mecheria",
    NAA: "Narrabri",
    NAG: "Nagpur",
    NAH: "Tahuna-Sangihe Island",
    NAJ: "Nakhchivan",
    NAK: "Chaloem Phra Kiat",
    NAL: "Nalchik",
    NAN: "Nadi",
    NAP: "NÃ¡poli",
    NAS: "Nassau",
    NAT: "Natal",
    NAW: null,
    NAY: "Beijing",
    NBC: "Nizhnekamsk",
    NBE: "Enfidha",
    NBG: "New Orleans",
    NBO: "Nairobi",
    NBS: "Baishan",
    NBW: "Guantanamo Bay Naval Station",
    NBX: "Nabire-Papua Island",
    NCA: "North Caicos",
    NCE: "Nice",
    NCL: "Newcastle",
    NCO: "North Kingstown",
    NCS: "Newcastle",
    NCU: "Nukus",
    NCY: "Annecy/Meythet",
    NDB: "Nouadhibou",
    NDC: "Nanded",
    NDD: "Sumbe",
    NDG: "Qiqihar",
    NDJ: "N'Djamena",
    NDR: "Nador",
    NDU: "Rundu",
    NEC: "Necochea",
    NEL: "Lakehurst",
    NER: "Neryungri",
    NEU: null,
    NEV: "Charlestown",
    NEW: "New Orleans",
    NFG: "Nefteyugansk",
    NFL: "Fallon",
    NGA: null,
    NGB: "Ningbo",
    NGE: "N'GaoundÃ©rÃ©",
    NGF: "Kaneohe",
    NGO: "Tokoname",
    NGQ: "Shiquanhe",
    NGS: "Nagasaki",
    NGU: "Norfolk",
    NHD: "Dubai",
    NHK: "Patuxent River",
    NHT: "London",
    NHV: "Nuku Hiva",
    NHZ: "Brunswick",
    NIM: "Niamey",
    NIP: "Jacksonville",
    NIT: "Niort/SouchÃ©",
    NJA: "Ayase / Yamato",
    NJC: "Nizhnevartovsk",
    NJF: "Najaf",
    NJK: "El Centro",
    NKC: "Nouakchott",
    NKG: "Nanjing",
    NKM: "Nagoya",
    NKT: "ÅžÄ±rnak",
    NKW: "Diego Garcia",
    NKX: "San Diego",
    NLA: "Ndola",
    NLC: "Lemoore",
    NLD: "Nuevo Laredo",
    NLH: "Ninglang",
    NLI: "Nikolayevsk-na-Amure Airport",
    NLK: "Burnt Pine",
    NLO: "N'dolo",
    NLT: "Xinyuan",
    NLU: "Mexico City (Santa Lucia)",
    NLV: "Nikolayev",
    NMB: "Daman",
    NMC: "Normans Cay",
    NMF: "Noonu Atoll",
    NMS: "Namsang",
    NNA: "Kenitra",
    NNG: "Nanning (Jiangnan)",
    NNM: "Naryan Mar",
    NNT: null,
    NOA: "Nowra Hill",
    NOB: "Nicoya",
    NOC: "Charlestown",
    NOJ: "Noyabrsk",
    NOP: "Sinop",
    NOS: "Nosy Be",
    NOU: "NoumÃ©a (La Tontouta)",
    NOV: "Huambo",
    NOZ: "Novokuznetsk",
    NPA: "Pensacola",
    NPE: "Napier",
    NPL: "New Plymouth",
    NPO: "Nanga Pinoh-Borneo Island",
    NQA: "Millington",
    NQI: "Kingsville",
    NQN: "Neuquen",
    NQT: "Nottingham",
    NQX: "Key West",
    NQY: "Newquay",
    NQZ: "Nur-Sultan",
    NRA: "Narrandera",
    NRB: "Mayport",
    NRK: "Norrköping",
    NRN: "Weeze",
    NRT: "Tokyo",
    NSE: "Milton",
    NSH: "Nowshahr",
    NSI: "YaoundÃ©",
    NSK: "Norilsk",
    NSN: "Nelson",
    NST: "Nakhon Si Thammarat",
    NSY: "Sigonella (CT)",
    NTB: "Notodden",
    NTD: "Point Mugu",
    NTE: "Nantes",
    NTL: "Williamtown",
    NTN: "Normanton",
    NTQ: "Wajima",
    NTR: "Monterrey",
    NTU: "Virginia Beach",
    NTX: "Ranai-Natuna Besar Island",
    NUE: "Nuremberg",
    NUI: "Nuiqsut",
    NUM: "Neom",
    NUQ: "Mountain View",
    NUW: "Oak Harbor",
    NUX: "Novy Urengoy",
    NVA: "Neiva",
    NVI: "Navoi",
    NVS: "Nevers/Fourchambault",
    NVT: "Navegantes",
    NWA: "Fomboni",
    NWI: "Norwich",
    NYA: "Nyagan",
    NYI: "Sunyani",
    NYK: "Nanyuki",
    NYM: "Nadym",
    NYO: "Stockholm",
    NYT: "Pyinmana",
    NZC: "Nazca",
    NZH: null,
    NZL: "Zhalantun",
    NZY: "San Diego",
    OAG: "Orange",
    OAI: "Bagram",
    OAJ: "Richlands",
    OAK: "Oakland",
    OAM: null,
    OAX: "Oaxaca",
    OBF: "WeÃŸling",
    OBO: "Obihiro",
    OBS: "Aubenas/ArdÃ¨che MÃ©ridional",
    OCC: "Coca",
    OCJ: "Boscobel",
    OCV: "OcaÃ±a",
    ODB: "CÃ³rdoba",
    ODE: "Odense",
    ODH: "Odiham",
    ODS: "Odessa",
    OEC: "Oecussi-Ambeno",
    OEL: "Orel",
    OER: "Ã–rnsköldsvik",
    OFF: "Omaha",
    OFK: "Norfolk",
    OGB: "Orangeburg",
    OGD: "Ogden",
    OGG: "Kahului",
    OGL: "Ogle",
    OGN: "Yonaguni",
    OGU: "Ordu",
    OGX: "Ouargla",
    OGZ: "Beslan",
    OHA: null,
    OHD: "Ohrid",
    OHE: "Mohe",
    OHO: "Okhotsk",
    OIM: "Izu Oshima",
    OIR: "Okushiri Island",
    OIT: "Oita",
    OKA: "Naha",
    OKC: "Oklahoma City",
    OKD: "Sapporo",
    OKE: "Wadomari",
    OKI: "Okinoshima",
    OKJ: "Okayama",
    OKL: "Oksibil-Papua Island",
    OKN: "Okondja",
    OKO: "Fussa",
    OKY: null,
    OLA: "Ã˜rland",
    OLB: "Olbia (SS)",
    OLF: "Wolf Point",
    OLL: "Oyo",
    OLM: "Olympia",
    OLS: "Nogales",
    OLZ: "Olyokminsk",
    OMA: "Omaha",
    OMB: "Omboue",
    OMC: "Ormoc City",
    OMD: "Oranjemund",
    OME: "Nome",
    OMH: "Urmia",
    OMO: "Mostar",
    OMR: "Oradea",
    OMS: "Omsk",
    OND: "Ondangwa",
    ONJ: "Kitaakita",
    ONP: "Newport",
    ONQ: "Zonguldak",
    ONT: "Ontario",
    ONX: "ColÃ³n",
    OOL: "Gold Coast",
    OOM: "Cooma",
    OPF: "Miami",
    OPO: "Porto",
    OPU: "Balimo",
    ORA: "OrÃ¡n",
    ORB: "Ã–rebro",
    ORD: "Chicago",
    ORF: "Norfolk",
    ORH: "Worcester",
    ORK: "Cork",
    ORN: "Oran",
    ORT: "Northway",
    ORU: "Oruro",
    ORY: "Paris",
    OSD: "Ã–stersund",
    OSF: "Moscow",
    OSH: "Oshkosh",
    OSI: "Osijek",
    OSL: "Oslo",
    OSM: "Mosul",
    OSN: null,
    OSR: "Ostrava",
    OSS: "Osh",
    OST: "Ostend",
    OSU: "Columbus",
    OSW: "Orsk",
    OTH: "North Bend",
    OTI: "Gotalalamo-Morotai Island",
    OTM: "Ottumwa",
    OTP: "Bucharest",
    OTR: "Corredores",
    OTZ: "Kotzebue",
    OUA: "Ouagadougou",
    OUD: "Oujda",
    OUE: null,
    OUH: "Oudtshoorn",
    OUL: "Oulu / Oulunsalo",
    OVB: "Novosibirsk",
    OVD: "RanÃ³n",
    OVS: "Sovetskiy",
    OWB: "Owensboro",
    OWD: "Norwood",
    OXB: "Bissau",
    OXF: "Kidlington",
    OXR: "Oxnard",
    OYA: "Goya",
    OYE: "Oyem",
    OYK: "Oiapoque",
    OYO: "Tres Arroyos",
    OYP: "Saint-Georges-de-l'Oyapock Airport",
    OZC: "Ozamiz City",
    OZH: "Zaporizhia",
    OZP: "MorÃ³n",
    OZR: "Fort Rucker/Ozark",
    OZZ: "Ouarzazate",
    PAB: "Bilaspur",
    PAC: "Albrook",
    PAD: "Paderborn",
    PAE: "Everett",
    PAG: "Pagadian City",
    PAH: "Paducah",
    PAL: "La Dorada",
    PAM: "Panama City",
    PAN: null,
    PAP: "Port-au-Prince",
    PAQ: "Palmer",
    PAT: "Patna",
    PAV: "Paulo Afonso",
    PAX: "Port-de-Paix",
    PAZ: "Poza Rica",
    PBC: "Puebla",
    PBD: "Porbandar",
    PBF: "Pine Bluff",
    PBG: "Plattsburgh",
    PBH: "Paro",
    PBI: "West Palm Beach",
    PBL: null,
    PBM: "Zandery",
    PBN: "Port Amboim",
    PBO: "Paraburdoo",
    PBR: "Puerto Barrios",
    PBU: "Putao",
    PBZ: "Plettenberg Bay",
    PCF: "Potchefstroom",
    PCL: "Pucallpa",
    PCP: "Sao Tome & Principe",
    PCR: "Puerto CarreÃ±o",
    PDA: "Puerto Inrida",
    PDG: "Padang (Katapiang)",
    PDK: "Atlanta",
    PDL: "Ponta Delgada",
    PDO: "Talang Gudang-Sumatra Island",
    PDP: "Punta del Este",
    PDS: null,
    PDT: "Pendleton",
    PDV: "Plovdiv",
    PDX: "Portland",
    PED: "Pardubice",
    PEE: "Perm",
    PEG: "Perugia",
    PEH: "PehuajÃ³",
    PEI: "Pereira",
    PEK: "Beijing",
    PEM: "Puerto Maldonado",
    PEN: "Penang",
    PER: "Perth",
    PES: "Petrozavodsk",
    PET: "Pelotas",
    PEV: "PÃ©cs-PogÃ¡ny",
    PEW: "Peshawar",
    PEX: "Pechora",
    PEZ: "Penza",
    PFB: "Passo Fundo",
    PFO: "Paphos",
    PGA: "Page",
    PGD: "Punta Gorda",
    PGF: "Perpignan/Rivesaltes",
    PGH: "Pantnagar",
    PGU: "Asalouyeh",
    PGV: "Greenville",
    PGX: "PÃ©rigueux/Bassillac",
    PGZ: "Ponta Grossa",
    PHB: "Parnaiba",
    PHC: "Port Harcourt",
    PHE: "Port Hedland",
    PHF: "Newport News",
    PHL: "Philadelphia",
    PHS: null,
    PHW: "Phalaborwa",
    PHX: "Phoenix",
    PHY: null,
    PIA: "Peoria",
    PIB: "Moselle",
    PIE: "St Petersburg-Clearwater",
    PIF: "Pingtung",
    PIH: "Pocatello",
    PIK: "Prestwick, South Ayrshire",
    PIL: "Pilar",
    PIO: "Pisco",
    PIR: "Pierre",
    PIS: "Poitiers/Biard",
    PIT: "Pittsburgh",
    PIU: "Piura",
    PIW: "Pikwitonei",
    PIX: "Pico Island",
    PIZ: "Point Lay",
    PJA: null,
    PJG: "Panjgur",
    PJM: "Puerto Jimenez",
    PKB: "Parkersburg",
    PKC: "Petropavlovsk-Kamchatsky",
    PKE: "Parkes",
    PKP: null,
    PKR: "Pokhara",
    PKT: "Wadeye",
    PKU: "Pekanbaru-Sumatra Island",
    PKV: "Pskov",
    PKW: "Selebi Phikwe",
    PKX: "Beijing",
    PKZ: "Pakse",
    PLJ: "Placencia",
    PLL: "Manaus",
    PLM: "Palembang",
    PLN: "Pellston",
    PLO: "Port Lincoln",
    PLQ: "Palanga",
    PLS: "Providenciales",
    PLU: "Belo Horizonte",
    PLW: "Palu",
    PLX: "Semey",
    PLZ: "Port Elizabeth",
    PMA: "Chake Chake",
    PMC: "Puerto Montt",
    PMD: "Palmdale",
    PMF: "Parma",
    PMG: "Ponta PorÃ£",
    PMI: "Palma De Mallorca",
    PMO: "Palermo",
    PMQ: "Perito Moreno",
    PMR: null,
    PMS: "Tadmur",
    PMV: "Isla Margarita",
    PMW: "Palmas",
    PMY: "Puerto Madryn",
    PMZ: "Palmar Sur",
    PNA: "Pamplona",
    PNB: "Porto Nacional",
    PNC: "Ponca City",
    PND: "Punta Gorda",
    PNE: "Philadelphia",
    PNH: "Phnom Penh (Pou Senchey)",
    PNI: "Pohnpei Island",
    PNK: "Pontianak-Borneo Island",
    PNL: "Pantelleria (TP)",
    PNP: "Popondetta",
    PNQ: "Pune",
    PNR: "Pointe Noire",
    PNS: "Pensacola",
    PNT: "Puerto Natales",
    PNV: "PanevÄ—Å¾ys",
    PNY: "Puducherry (Pondicherry)",
    PNZ: "Petrolina",
    POA: "Porto Alegre",
    POB: "Fayetteville",
    POE: "Fort Polk",
    POG: "Port Gentil",
    POI: "Potosia",
    POL: "Pemba / Porto Amelia",
    POM: "Port Moresby",
    POO: "PoÃ§os De Caldas",
    POP: "Puerto Plata",
    POR: "Pori",
    POS: "Port of Spain",
    POT: "Ken Jones",
    POU: "Poughkeepsie",
    POW: "PortoroÅ¾",
    POX: "Cormeilles-en-Vexin",
    POZ: "PoznaÅ„",
    PPB: "Presidente Prudente",
    PPG: "Pago Pago",
    PPI: null,
    PPK: "Petropavl",
    PPN: "PopayÃ¡n",
    PPP: "Proserpine",
    PPQ: null,
    PPS: "Puerto Princesa City",
    PPT: "Papeete",
    PQC: "Phu Quoc Island",
    PQI: "Presque Isle",
    PQQ: "Port Macquarie",
    PRA: "Parana",
    PRB: "Paso Robles",
    PRC: "Prescott",
    PRG: "Prague",
    PRH: null,
    PRI: "Grand Anse",
    PRM: "PortimÃ£o",
    PRN: "Prishtina",
    PRV: "PÅ™erov",
    PRX: "Paris",
    PRY: "Pretoria",
    PSA: "Pisa",
    PSC: "Pasco",
    PSD: "Port Said",
    PSE: "Ponce",
    PSG: "Petersburg",
    PSI: "Pasni",
    PSJ: "Poso-Celebes Island",
    PSM: "Portsmouth",
    PSO: "Pasto",
    PSP: "Palm Springs",
    PSR: "Pescara",
    PSS: "Posadas",
    PSU: "Putussibau-Borneo Island",
    PSY: "Stanley",
    PSZ: "Puerto SuÃ¡rez",
    PTG: "Polokwane",
    PTH: "Port Heiden",
    PTJ: null,
    PTK: "Pontiac",
    PTM: "Palmarito",
    PTP: "Pointe-Ã -Pitre",
    PTU: "Platinum",
    PTX: "Pitalito",
    PTY: "Tocumen",
    PUB: "Pueblo",
    PUD: "Puerto Deseado",
    PUF: "Pau/PyrÃ©nÃ©es (Uzein)",
    PUG: null,
    PUJ: "Punta Cana",
    PUQ: "Punta Arenas",
    PUS: "Busan",
    PUT: "Puttaparthi",
    PUU: "Puerto Asis",
    PUW: "Pullman/Moscow",
    PUY: "Pula",
    PUZ: "Puerto Cabezas",
    PVA: "Providencia",
    PVD: "Providence",
    PVG: "Shanghai (Pudong)",
    PVH: "Porto Velho",
    PVK: "Preveza/Lefkada",
    PVO: "Portoviejo",
    PVR: "Puerto Vallarta",
    PVS: "Chukotka",
    PVU: "Provo",
    PWE: "Apapelgino",
    PWK: "Chicago/Prospect Heights/Wheeling",
    PWM: "Portland",
    PWQ: "Pavlodar",
    PWT: "Bremerton",
    PWY: "Pinedale",
    PXM: "Puerto Escondido",
    PXO: "Vila Baleira",
    PXR: "Surin",
    PXU: "Pleiku",
    PYH: "Puerto Ayacucho",
    PYJ: "Yakutia",
    PYK: "Karaj",
    PYR: "Andravida",
    PZA: "Paz De Ariporo",
    PZB: "Pietermaritzburg",
    PZH: "Fort Sandeman",
    PZI: "Panzhihua",
    PZO: "Puerto Ordaz-Ciudad Guayana",
    PZS: "Temuco",
    PZU: "Port Sudan",
    PZY: "PieÅ¡Å¥any",
    QBC: "Bella Coola",
    QCY: "Coningsby",
    QGU: "Gifu",
    QHR: "Debre Zeyit",
    QJB: "Jubail",
    QLD: "Blida",
    QLR: null,
    QMJ: "Masjed Soleyman",
    QOW: "Owerri",
    QPG: "Paya Lebar",
    QPS: "Pirassununga",
    QRA: "Johannesburg",
    QRM: null,
    QRO: "QuerÃ©taro",
    QRR: null,
    QRW: "Warri",
    QSF: "SÃ©tif",
    QSN: "San NicolÃ¡s",
    QSR: "Salerno",
    QSZ: "Shache",
    QUO: "Uyo",
    QUY: "St. Ives",
    RAB: "Kokopo",
    RAE: "Arar",
    RAH: "Rafha",
    RAI: "Praia",
    RAJ: "Rajkot",
    RAK: "Marrakech",
    RAL: "Riverside",
    RAO: "RibeirÃ£o Preto",
    RAP: "Rapid City",
    RAR: "Avarua",
    RAS: "Rasht",
    RAZ: "Rawalakot",
    RBA: "Rabat",
    RBE: "Ratanakiri",
    RBL: "Red Bluff",
    RBR: "Rio Branco",
    RBY: "Ruby",
    RCA: "Rapid City",
    RCB: "Richards Bay",
    RCH: "Riohacha",
    RCO: "Rochefort/Saint-Agnant",
    RCQ: "Reconquista",
    RCU: "Rio Cuarto",
    RDD: "Redding",
    RDG: "Reading",
    RDM: "Redmond",
    RDO: "Radom",
    RDP: "Durgapur",
    RDR: "Grand Forks",
    RDS: "Rincon de los Sauces",
    RDU: "Raleigh/Durham",
    RDZ: "Rodez/Marcillac",
    REA: "Reao",
    REC: "Recife",
    REG: "Reggio Calabria",
    REL: "Rawson",
    REN: "Orenburg",
    REP: "Siem Reap",
    RER: "Retalhuleu",
    RES: "Resistencia",
    REU: "Reus",
    REW: "Rewa",
    REX: "Reynosa",
    RFD: "Chicago/Rockford",
    RFP: "Uturoa",
    RGA: "Rio Grande",
    RGI: null,
    RGK: "Gorno-Altaysk",
    RGL: "Rio Gallegos",
    RGN: "Yangon",
    RGO: "Hoemun-ri",
    RGS: "Burgos",
    RGT: "Rengat-Sumatra Island",
    RHD: "Termas de Rio Hondo",
    RHI: "Rhinelander",
    RHO: "Rodes Island",
    RIA: "Santa Maria",
    RIC: "Richmond",
    RIJ: "Rioja",
    RIL: "Rifle",
    RIS: "Rishiri",
    RIV: "Riverside",
    RIW: "Riverton",
    RIX: "Riga",
    RIY: "Riyan",
    RIZ: "Rizhao",
    RJA: "Rajahmundry",
    RJH: "Rajshahi",
    RJK: "Rijeka",
    RJL: "LogroÃ±o",
    RJN: "Rafsanjan",
    RKE: "Copenhagen",
    RKS: "Rock Springs",
    RKT: "Ras Al Khaimah",
    RKV: "Reykjavik",
    RKZ: "XigazÃª",
    RLG: "Rostock",
    RLK: "Bavannur",
    RMA: "Roma",
    RME: "Rome",
    RMF: "Marsa Alam",
    RMG: "Rome",
    RMI: "Rimini",
    RMK: null,
    RML: "Colombo",
    RMQ: "Taichung (Qingshui)",
    RMS: "Ramstein",
    RMU: "Corvera",
    RNB: "Ronneby",
    RND: "Universal City",
    RNE: "Roanne/Renaison",
    RNJ: "Yoron",
    RNN: "RÃ¸nne",
    RNO: "Reno",
    RNS: "Rennes/Saint-Jacques",
    ROA: "Roanoke",
    ROB: "Monrovia",
    ROC: "Rochester",
    ROD: "Robertson",
    ROI: null,
    ROK: "Rockhampton",
    ROO: "RondonÃ³polis",
    ROP: "Rota Island",
    ROR: "Babelthuap Island",
    ROS: "Rosario",
    ROT: "Rotorua",
    ROV: "Rostov-on-Don",
    ROW: "Roswell",
    ROZ: "Rota",
    RPM: null,
    RPN: "Rosh Pina",
    RQA: "Ruoqiang Town",
    RQW: "Qayyarah",
    RRG: "Port Mathurin",
    RRK: null,
    RRS: "RÃ¸ros",
    RSA: "Santa Rosa",
    RSD: "Rock Sound",
    RSL: "Russell",
    RST: "Rochester",
    RSU: "Yeosu",
    RSW: "Fort Myers",
    RTB: "RoatÃ¡n",
    RTC: null,
    RTE: "SÃ£o Paulo",
    RTM: "Rotterdam",
    RUA: "Arua",
    RUG: "Rugao",
    RUH: "Riyadh",
    RUI: "Alto",
    RUN: "St Denis",
    RUR: null,
    RUT: "Rutland",
    RUV: "Rubelsanto",
    RVK: "RÃ¸rvik",
    RVN: "Rovaniemi",
    RVS: "Tulsa",
    RWF: "Redwood Falls",
    RWI: "Rocky Mount",
    RWL: "Rawlins",
    RWN: "Rivne",
    RXS: "Roxas City",
    RYB: "Rybinsk",
    RYG: "Oslo",
    RYK: "Rahim Yar Khan",
    RYN: "Royan/MÃ©dis",
    RZA: "Puerto Santa Cruz",
    RZE: "RzeszÃ³w",
    RZR: "Ramsar",
    RZV: "Rize",
    SAC: "Sacramento",
    SAF: "Santa Fe",
    SAG: "Kakadi",
    SAH: "Sana'a",
    SAL: "San Salvador (San Luis Talpa)",
    SAN: "San Diego",
    SAP: "San Pedro Sula",
    SAQ: "Andros Island",
    SAT: "San Antonio",
    SAV: "Savannah",
    SAW: "Pendik, Istanbul",
    SAY: "Siena",
    SBA: "Santa Barbara",
    SBD: "San Bernardino",
    SBH: "Gustavia / Saint-Jean",
    SBK: "Saint-Brieuc/Armor",
    SBL: "Santa Ana del Yacuma",
    SBN: "South Bend",
    SBP: "San Luis Obispo",
    SBT: "Sabetta",
    SBU: "Springbok",
    SBW: "Sibu",
    SBY: "Salisbury",
    SBZ: "Sibiu",
    SCC: "Deadhorse",
    SCE: "State College",
    SCH: "Schenectady",
    SCI: null,
    SCK: "Stockton",
    SCL: "Santiago",
    SCM: "Scammon Bay",
    SCN: "Saarbrücken",
    SCO: "Aktau",
    SCQ: "Santiago de Compostela",
    SCR: "Sälen / Trysil",
    SCS: "Shetland Islands",
    SCT: "Socotra Islands",
    SCU: "Santiago",
    SCV: "Suceava",
    SCW: "Syktyvkar",
    SDB: "Langebaanweg",
    SDD: "Lubango",
    SDE: "Santiago del Estero",
    SDF: "Louisville",
    SDG: null,
    SDJ: "Natori",
    SDK: "Sandakan",
    SDL: "Sundsvall/ Härnösand",
    SDM: "San Diego",
    SDP: "Sand Point",
    SDQ: "Santo Domingo",
    SDR: "Santander",
    SDS: "Sado",
    SDT: "Saidu Sharif",
    SDU: "Rio de Janeiro",
    SDY: "Sidney",
    SEA: "Seattle",
    SEB: "Sabha",
    SEK: "Srednekolymsk",
    SEN: "London",
    SEZ: "Mahe Island",
    SFA: "Sfax",
    SFB: "Orlando",
    SFD: "Inglaterra",
    SFE: null,
    SFF: "Spokane",
    SFG: "Grand Case",
    SFJ: "Kangerlussuaq",
    SFN: "Santa Fe",
    SFO: "San Francisco",
    SFQ: "ÅžanlÄ±urfa",
    SFS: "Olongapo",
    SFT: "SkellefteÃ¥",
    SGC: "Surgut",
    SGD: "SÃ¸nderborg",
    SGE: null,
    SGF: "Springfield",
    SGH: "Springfield",
    SGI: "Sargodha",
    SGL: "Cavite",
    SGN: "Ho Chi Minh City",
    SGR: "Houston",
    SGU: "St George",
    SGZ: null,
    SHA: "Shanghai (Minhang)",
    SHB: "Nakashibetsu",
    SHD: "Weyers Cave",
    SHE: "Hunnan, Shenyang",
    SHH: "Shishmaref",
    SHI: "Miyakojima",
    SHJ: "Sharjah",
    SHL: "Shillong",
    SHM: "Shirahama",
    SHO: "Mpaka",
    SHR: "Sheridan",
    SHS: "Jingzhou",
    SHT: null,
    SHV: "Shreveport",
    SHW: "Sharurah",
    SIA: "Xi'an",
    SID: "Espargos",
    SIG: "San Juan",
    SIJ: "SiglufjörÃ°ur",
    SIN: "Singapore",
    SIO: null,
    SIP: "Simferopol",
    SIR: "Sion",
    SIS: "Sishen",
    SIT: "Sitka",
    SJC: "San Jose",
    SJD: "San JosÃ© del Cabo",
    SJE: "San JosÃ© Del Guaviare",
    SJI: "San Jose",
    SJJ: "Sarajevo",
    SJK: "SÃ£o JosÃ© Dos Campos",
    SJL: "SÃ£o Gabriel Da Cachoeira",
    SJO: "San JosÃ© (Alajuela)",
    SJP: "SÃ£o JosÃ© Do Rio Preto",
    SJT: "San Angelo",
    SJU: "San Juan",
    SJW: "Shijiazhuang",
    SJX: "Sartaneja",
    SJY: "Seinäjoki / Ilmajoki",
    SJZ: "Velas",
    SKA: "Spokane",
    SKB: "Basseterre",
    SKD: "Samarkand",
    SKE: "Geiteryggen",
    SKF: "San Antonio",
    SKG: "Thessaloniki",
    SKN: "Hadsel",
    SKO: "Sokoto",
    SKP: "Skopje",
    SKS: "Vojens",
    SKT: "Sialkot",
    SKV: "Saint Catherine",
    SKX: "Saransk",
    SKZ: "Mirpur Khas",
    SLA: "Salta",
    SLC: "Salt Lake City",
    SLD: "Sliac",
    SLE: "Salem",
    SLK: "Saranac Lake",
    SLL: "Salalah",
    SLM: "Salamanca",
    SLN: "Salina",
    SLP: "San Luis Potosia",
    SLU: "Castries",
    SLW: "Saltillo",
    SLY: "Salekhard",
    SLZ: "Sao Luis",
    SMA: "Vila do Porto",
    SME: "Somerset",
    SMF: "Sacramento",
    SMI: "Samos Island",
    SML: "Stella Maris",
    SMN: "Salmon",
    SMO: "Santa Monica",
    SMR: "Santa Marta",
    SMS: "Vohilava",
    SMV: null,
    SMW: "Smara",
    SMX: "Santa Maria",
    SNA: "Santa Ana",
    SNB: null,
    SNC: "Salinas",
    SNE: "PreguiÃ§a",
    SNF: "San Felipe",
    SNJ: "Pinar Del Rio",
    SNN: "Shannon",
    SNO: null,
    SNP: "St Paul Island",
    SNR: "Saint-Nazaire/Montoir",
    SNS: "Salinas",
    SNU: "Santa Clara",
    SNV: null,
    SNW: "Thandwe",
    SNY: "Sidney",
    SNZ: "Rio de Janeiro",
    SOB: "SÃ¡rmellÃ©k",
    SOF: "Sofia",
    SOJ: "SÃ¸rkjosen",
    SOM: "El Tigre",
    SON: "Luganville",
    SOO: "Söderhamn",
    SOQ: "Sorong-Papua Island",
    SOT: "Sodankyla",
    SOU: "Southampton",
    SOZ: "Solenzara",
    SPC: "Sta Cruz de la Palma, La Palma Island",
    SPD: "Saidpur",
    SPI: "Springfield",
    SPM: "Trier",
    SPN: "I Fadang, Saipan",
    SPP: "Menongue",
    SPR: "San Pedro",
    SPS: "Wichita Falls",
    SPU: "Split",
    SPX: "Giza",
    SPY: null,
    SQD: "Shangrao",
    SQG: "Sintang-Borneo Island",
    SQJ: "Sanming",
    SQO: "Storuman",
    SQQ: "Å iauliai",
    SQW: "Skive",
    SQZ: "Scampton",
    SRE: "Yamparaez",
    SRP: "Leirvik",
    SRQ: "Sarasota/Bradenton",
    SRT: "Soroti",
    SRX: "Sirt",
    SRY: "Sari",
    SRZ: "Santa Cruz",
    SSA: "Salvador",
    SSC: "Sumter",
    SSE: "Solapur",
    SSF: "San Antonio",
    SSG: "Malabo",
    SSH: "Sharm el-Sheikh",
    SSI: "St Simons Island",
    SSJ: "Alstahaug",
    SSN: "Seongnam",
    SST: "Santa Teresita",
    SSY: "Mbanza Congo",
    SSZ: "GuarujÃ¡",
    STA: "Skjern / RingkÃ¸bing",
    STB: null,
    STC: "Saint Cloud",
    STD: "Santo Domingo",
    STG: "St George",
    STI: "Santiago",
    STJ: "St Joseph",
    STL: "St Louis",
    STM: "SantarÃ©m",
    STN: "London",
    STP: "St Paul",
    STR: "Stuttgart",
    STS: "Santa Rosa",
    STT: "Charlotte Amalie",
    STV: null,
    STW: "Stavropol",
    STX: "Christiansted",
    STY: "Salto",
    SUB: "Surabaya",
    SUF: "Lamezia Terme (CZ)",
    SUG: "Surigao City",
    SUI: "Sukhumi",
    SUJ: "Satu Mare",
    SUL: "Sui",
    SUN: "Hailey",
    SUS: "St Louis",
    SUU: "Fairfield",
    SUV: "Nausori",
    SUX: "Sioux City",
    SVA: "Savoonga",
    SVB: "Sambava",
    SVD: "Kingstown",
    SVG: "Stavanger",
    SVI: "San Vicente Del CaguÃ¡n",
    SVJ: "SvolvÃ¦r",
    SVL: "Savonlinna",
    SVN: "Savannah",
    SVO: "Moscow",
    SVP: "Kuito",
    SVQ: "Sevilla",
    SVW: "Sparrevohn",
    SVX: "Yekaterinburg",
    SVZ: null,
    SWA: "Jieyang (Rongcheng)",
    SWC: null,
    SWD: "Seward",
    SWF: "Newburgh",
    SWH: null,
    SWO: "Stillwater",
    SWS: "Swansea",
    SWT: "Strezhevoy",
    SWU: "Suwon",
    SWV: "Evensk",
    SXB: "Strasbourg",
    SXE: "Sale",
    SXI: "Siri",
    SXJ: "Shanshan",
    SXL: "Sligo",
    SXM: "Saint Martin",
    SXN: "Sowa",
    SXQ: "Soldotna",
    SXR: "Srinagar",
    SXV: "Salem",
    SXZ: "Siirt",
    SYA: "Shemya",
    SYD: "Sydney",
    SYJ: "Sirjan",
    SYO: "Shonai",
    SYP: "Santiago",
    SYQ: "San Jose",
    SYR: "Syracuse",
    SYS: "Saskylakh",
    SYT: "Saint-Yan",
    SYW: "Sehwan Sharif",
    SYX: "Sanya (Tianya)",
    SYY: "Stornoway, Western Isles",
    SYZ: "Shiraz",
    SZA: "Soyo",
    SZB: "Subang",
    SZF: "Samsun",
    SZG: "Salzburg",
    SZJ: "Isla de la Juventud",
    SZK: "Skukuza",
    SZL: "Knob Noster",
    SZV: "Suzhou",
    SZW: null,
    SZX: "Shenzhen (Bao'an)",
    SZY: "Olsztyn",
    SZZ: "Goleniow",
    TAB: "Scarborough",
    TAC: "Tacloban City",
    TAE: "Daegu",
    TAF: "Tafraoui",
    TAG: "Panglao",
    TAH: null,
    TAI: "Ta'izz",
    TAK: "Takamatsu",
    TAM: "Tampico",
    TAO: "Jiaozhou, Qingdao",
    TAP: "Tapachula",
    TAR: "Grottaglie",
    TAS: "Tashkent",
    TAT: "Poprad",
    TAY: "Tartu",
    TAZ: "DaÅŸoguz",
    TBB: "Tuy Hoa",
    TBF: null,
    TBH: "Tablas Island",
    TBI: "Cat Island",
    TBJ: "Tabarka",
    TBN: "Fort Leonard Wood",
    TBP: "Tumbes",
    TBS: "Tbilisi",
    TBT: "Tabatinga",
    TBU: "Nuku'alofa",
    TBW: "Tambov",
    TBZ: "Tabriz",
    TCA: "Tennant Creek",
    TCB: "Treasure Cay",
    TCC: "Tucumcari",
    TCE: "Tulcea",
    TCL: "Tuscaloosa",
    TCM: "Tacoma",
    TCO: "Tumaco",
    TCP: "Taba",
    TCQ: "Tacna",
    TCS: "Truth or Consequences",
    TCX: "Tabas",
    TCZ: "Tengchong",
    TDD: "Trinidad",
    TDG: "Tandag",
    TDK: "Taldykorgan",
    TDL: "Tandil",
    TDX: "Laem Ngop",
    TEA: "Tela",
    TEB: "Teterboro",
    TEC: "TelÃªmaco Borba",
    TED: "Thisted",
    TEE: "TÃ©bessi",
    TEF: null,
    TEM: "Temora",
    TEQ: "Ã‡orlu",
    TER: "Praia da VitÃ³ria",
    TET: "Tete",
    TEU: null,
    TEV: "Teruel",
    TEZ: null,
    TFF: "TefÃ©",
    TFN: "Tenerife",
    TFS: "Tenerife",
    TFU: "Jianyang, Chengdu",
    TGA: "Western Water Catchment",
    TGD: "Podgorica",
    TGG: "Kuala Terengganu",
    TGJ: "Tiga",
    TGK: "Taganrog",
    TGM: "TÃ¢rgu MureÅŸ",
    TGN: "Morwell",
    TGO: "Tongliao",
    TGP: "Bor",
    TGR: "Touggourt",
    TGT: "Tanga",
    TGU: "Tegucigalpa",
    TGZ: "Tuxtla GutiÃ©rrez",
    THE: "Teresina",
    THG: "Biloela",
    THL: "Tachileik",
    THN: "Trollhättan",
    THQ: "Tianshui",
    THR: "Tehran",
    THS: null,
    THU: "Thule",
    THZ: "Tahoua",
    TIA: "Tirana",
    TID: "Tiaret",
    TIF: "Taâ€™if",
    TIH: null,
    TIJ: "Tijuana",
    TIK: "Oklahoma City",
    TIM: "Timika-Papua Island",
    TIN: "Tindouf",
    TIP: "Tripoli",
    TIQ: "Tinian Island",
    TIU: null,
    TIV: "Tivat",
    TIW: "Tacoma",
    TIX: "Titusville",
    TJA: "Tarija",
    TJG: "Tanta-Tabalong-Borneo Island",
    TJH: "Toyooka",
    TJI: "Trujillo",
    TJK: "Tokat",
    TJM: "Tyumen",
    TJU: "Kulyab",
    TKA: "Talkeetna",
    TKC: "Tiko",
    TKD: "Sekondi-Takoradi",
    TKF: "Truckee",
    TKG: "Bandar Lampung-Sumatra Island",
    TKH: null,
    TKK: "Weno Island",
    TKN: "Amagi",
    TKP: null,
    TKS: "Tokushima",
    TKT: null,
    TKU: "Turku",
    TKX: null,
    TLC: "Toluca",
    TLE: "Toliara",
    TLH: "Tallahassee",
    TLJ: "Takotna",
    TLL: "Tallinn",
    TLM: "Tlemcen",
    TLN: "Toulon/HyÃ¨res/Le Palyvestre",
    TLQ: "Turpan",
    TLS: "Toulouse/Blagnac",
    TLV: "Tel Aviv",
    TLX: "Talca",
    TMB: "Miami",
    TME: "Tame",
    TMJ: "Termez",
    TML: "Tamale",
    TMM: "Toamasina",
    TMO: null,
    TMP: "Tampere / Pirkkala",
    TMR: "Tamanrasset",
    TMS: "SÃ£o TomÃ©",
    TMT: "OriximinÃ¡",
    TMW: "Tamworth",
    TMX: "Timimoun",
    TNA: "Jinan",
    TND: "Trinidad",
    TNE: "Tanegashima",
    TNF: "Toussus-le-Noble",
    TNG: "Tangier",
    TNH: "Tonghua",
    TNN: "Tainan (Rende)",
    TNR: "Antananarivo",
    TNW: "Tena",
    TOD: "Kampung Tekek",
    TOE: "Tozeur",
    TOF: "Tomsk",
    TOG: "Togiak Village",
    TOI: "Troy",
    TOJ: "Madrid",
    TOL: "Toledo",
    TOM: "Timbuktu",
    TOO: "Coto Brus",
    TOP: "Topeka",
    TOQ: "Tocopilla",
    TOS: "TromsÃ¸",
    TOU: "Touho",
    TOY: "Toyama",
    TPA: "Tampa",
    TPC: "Tarapoa",
    TPE: "Taipei",
    TPH: "Tonopah",
    TPJ: "Taplejung",
    TPL: "Temple",
    TPP: "Tarapoto",
    TPQ: "Tepic",
    TPS: "Trapani (TP)",
    TQD: "Al Habbaniyah",
    TQS: "Tres Esquinas",
    TRA: "Tarama",
    TRC: "TorreÃ³n",
    TRD: "Trondheim",
    TRE: "Balemartine",
    TRF: "Torp",
    TRG: "Tauranga",
    TRI: "Bristol/Johnson/Kingsport",
    TRK: "Tarakan Island",
    TRM: "Palm Springs",
    TRN: "Torino",
    TRO: "Taree",
    TRQ: "TarauacÃ¡",
    TRR: "Trincomalee",
    TRS: "Trieste",
    TRT: "Toraja",
    TRU: "Trujillo",
    TRV: "Thiruvananthapuram",
    TRW: "Tarawa",
    TRZ: "Tiruchirappalli",
    TSA: "Taipei City",
    TSB: "Tsumeb",
    TSF: "Treviso",
    TSJ: "Tsushima",
    TSN: "Tianjin",
    TSR: "TimiÅŸoara",
    TST: "Trang",
    TSV: "Townsville",
    TTA: "Tan Tan",
    TTB: "Arbatax",
    TTC: "Taltal",
    TTD: "Portland",
    TTE: "Sango-Ternate Island",
    TTG: "Tartagal",
    TTH: "Thumrait",
    TTJ: "Tottori",
    TTN: "Trenton",
    TTQ: "Roxana",
    TTT: "Taitung City",
    TTU: "TÃ©touan",
    TUA: "TulcÃ¡n",
    TUB: null,
    TUC: "San Miguel de TucumÃ¡n",
    TUD: "Tambacounda",
    TUF: "Tours/Val de Loire (Loire Valley)",
    TUG: "Tuguegarao City",
    TUI: "Turaif",
    TUK: "Turbat",
    TUL: "Tulsa",
    TUM: null,
    TUN: "Tunis",
    TUO: "Taupo",
    TUP: "Tupelo",
    TUR: "Tucurui",
    TUS: "Tucson",
    TUU: "Tabuk",
    TUV: "Tucupita",
    TVC: "Traverse City",
    TVL: "South Lake Tahoe",
    TVY: "Dawei",
    TWF: "Twin Falls",
    TWT: null,
    TWU: "Tawau",
    TWZ: "Twitzel",
    TXC: "Orsha",
    TXE: "Takengon",
    TXK: "Texarkana",
    TXN: "Huangshan",
    TYB: null,
    TYF: "Torsby",
    TYL: "Talara",
    TYM: null,
    TYN: "Taiyuan",
    TYR: "Tyler",
    TYS: "Knoxville",
    TZA: "Belize City",
    TZL: "Tuzla",
    TZN: "Andros",
    TZR: "TaszÃ¡r",
    TZX: "Trabzon",
    UAB: "SarÄ±Ã§am",
    UAI: "Suai",
    UAK: "Narsarsuaq",
    UAM: "Yigo, Mariana Island",
    UAQ: "San Juan",
    UAR: "Bouarfa",
    UBA: "Uberaba",
    UBJ: "Ube",
    UBN: "Ulaanbaatar (Sergelen)",
    UBP: "Ubon Ratchathani",
    UCB: "Ulanqab",
    UCT: "Ukhta",
    UDI: "UberlÃ¢ndia",
    UDJ: "Uzhhorod",
    UDR: "Udaipur",
    UEL: "Quelimane",
    UEO: "Kumejima",
    UET: "Quetta",
    UFA: "Ufa",
    UGA: "Bulgan",
    UGC: "Urgench",
    UGO: "Uige",
    UGU: "Sugapa-Papua Island",
    UHE: "UherskÃ© HradiÅ¡tÄ›",
    UIB: "QuibdÃ³",
    UIH: "Quy Nohn",
    UIN: "Quincy",
    UIO: "Quito",
    UIP: "Quimper/Pluguffan",
    UKB: "Kobe",
    UKI: "Ukiah",
    UKK: "Ust-Kamenogorsk (Oskemen)",
    UKS: "Sevastopol",
    UKX: "Ust-Kut",
    ULA: "San Julian",
    ULD: "Ulundi",
    ULH: "Al Ula",
    ULK: "Lensk",
    ULN: "Ulaanbaatar",
    ULP: null,
    ULQ: "TuluÃ¡",
    ULU: "Gulu",
    ULV: "Ulyanovsk",
    ULY: "Cherdakly",
    UME: "UmeÃ¥",
    UND: "Kunduz",
    UNI: "Union Island",
    UNN: null,
    UOX: "Oxford",
    UPB: "Havana",
    UPG: "Ujung Pandang-Celebes Island",
    UPL: "Upala",
    UPN: "Uruapan",
    URA: "Uralsk",
    URC: "Ãœrümqi",
    URE: "Kuressaare",
    URG: "Uruguaiana",
    URJ: "Uray",
    URO: "Rouen/VallÃ©e de Seine",
    URS: "Kursk",
    URT: "Surat Thani",
    URY: "Gurayat",
    USA: "Concord",
    USH: "Ushuaia",
    USK: "Usinsk",
    USM: "Na Thon (Ko Samui Island)",
    USN: "Ulsan",
    USR: "Ust-Nera",
    UST: "St Augustine",
    USU: "Coron",
    UTH: "Udon Thani",
    UTI: "Utti / Valkeala",
    UTN: "Upington",
    UTO: "Utopia Creek",
    UTP: "Rayong",
    UTS: "Ust-Tsylma",
    UTT: "Mthatha",
    UTW: "Queenstown",
    UUA: "Bugulma",
    UUD: "Ulan Ude",
    UUN: null,
    UUS: "Yuzhno-Sakhalinsk",
    UVE: "OuvÃ©a",
    UVF: "Vieux Fort",
    UYL: "Nyala",
    UZC: "UÅ¾ice",
    UZU: "Curuzu Cuatia",
    VAA: "Vaasa",
    VAD: "Valdosta",
    VAF: "Valence/Chabeuil",
    VAG: "Varginha",
    VAI: "Vanimo",
    VAM: "Maamigili",
    VAN: "Van",
    VAR: "Varna",
    VAV: "Vava'u Island",
    VAW: "VardÃ¸",
    VBG: "Lompoc",
    VBS: "Montichiari (BS)",
    VBY: "Visby",
    VCA: "Can Tho",
    VCE: "Venice",
    VCP: "Campinas",
    VCR: "Carora",
    VCS: "Con Dao",
    VCT: "Victoria",
    VDB: "Fagernes",
    VDC: "VitÃ³ria da Conquista",
    VDE: "El Hierro Island",
    VDH: "Dong Hoi",
    VDM: "Viedma / Carmen de Patagones",
    VDO: "Van Don",
    VDP: null,
    VDR: "Villa Dolores",
    VDS: "VadsÃ¸",
    VDZ: "Valdez",
    VEL: "Vernal",
    VER: "Veracruz",
    VEY: "Vestmannaeyjar",
    VFA: "Victoria Falls",
    VGA: "Gannavaram",
    VGD: "Vologda",
    VGO: "Vigo",
    VGT: "Las Vegas",
    VHC: "Saurimo",
    VHM: "Vilhelmina",
    VHY: "Vichy/Charmeil",
    VIE: "Vienna",
    VIG: "El Vigia",
    VII: "Vinh",
    VIL: "Dakhla",
    VIN: "Vinnitsa",
    VIR: "Durban",
    VIS: "Visalia",
    VIT: "Alava",
    VIX: "VitÃ³ria",
    VIY: "Villacoublay/VÃ©lizy",
    VKG: "Rach Gia",
    VKO: "Moscow",
    VKT: "Vorkuta",
    VLC: "Valencia",
    VLD: "Valdosta",
    VLG: "Villa Gesell",
    VLI: "Port Vila",
    VLL: "Valladolid",
    VLM: "Villamontes",
    VLN: "Valencia",
    VLR: "Vallenar",
    VLU: "Velikiye Luki",
    VLV: "Valera",
    VLY: "Angelsey",
    VME: "Villa Mercedes",
    VMU: "Baimuru",
    VNE: "Vannes/Meucon",
    VNO: "Vilnius",
    VNS: "Varanasi",
    VNT: "Ventspils",
    VNX: "Vilanculo",
    VNY: "Van Nuys",
    VOD: "Vodochody",
    VOG: "Volgograd",
    VOH: "Vohemar",
    VOK: "Camp Douglas",
    VOL: "Nea Anchialos",
    VOZ: "Voronezh",
    VPE: "Ngiva",
    VPS: "Valparaiso",
    VPY: "Chimoio",
    VPZ: "Valparaiso",
    VRA: "Varadero",
    VRB: "Vero Beach",
    VRC: "Virac",
    VRE: "Vredendal",
    VRK: "Varkaus / Joroinen",
    VRL: "Vila Real",
    VRN: "Villafranca di Verona",
    VRO: "Varadero",
    VRU: "Vyrburg",
    VSA: "Villahermosa",
    VSE: "Viseu",
    VSG: "Luhansk",
    VST: "Stockholm / VästerÃ¥s",
    VTB: "Vitebsk",
    VTE: "Vientiane",
    VTM: "Beersheba",
    VTN: "Valentine",
    VTU: "Las Tunas",
    VUP: "Valledupar",
    VVC: "Villavicencio",
    VVI: "Santa Cruz",
    VVO: "Artyom",
    VVZ: "Illizi",
    VXC: "Lichinga",
    VXE: "SÃ£o Pedro",
    VXO: "Växjö",
    VYI: "Vilyuisk",
    WAE: "Wadi Al Dawasir",
    WAG: "Wanganui",
    WAI: "Antsohihy",
    WAT: "Waterford",
    WAW: "Warsaw",
    WBG: "Jagel",
    WBM: "Wapenamanda",
    WCH: "Chaiten",
    WDH: "Windhoek",
    WDS: "Shiyan",
    WEF: "Weifang",
    WEH: "Weihai",
    WEI: "Weipa",
    WFI: "Fianarantsoa",
    WGA: "Wagga Wagga",
    WGE: null,
    WGN: "Shaoyang",
    WGT: null,
    WHB: null,
    WHK: null,
    WIC: "Wick",
    WIE: "Wiesbaden",
    WIL: "Nairobi",
    WIN: null,
    WIR: "Wairoa",
    WJF: "Lancaster",
    WJR: "Wajir",
    WJU: "Wonju",
    WKA: "Wanaka",
    WKB: null,
    WKF: "Pretoria",
    WKJ: "Wakkanai",
    WKK: "Aleknagik",
    WLG: "Wellington",
    WLS: "Wallis Island",
    WMC: "Winnemucca",
    WME: null,
    WMH: "Mountain Home",
    WMI: "Warsaw",
    WMN: "Maroantsetra",
    WMR: "Mananara Nord",
    WMT: "Zunyi",
    WMX: "Wamena, Jayawijaya Regency, Papua Province",
    WNI: "Wangi-wangi Island",
    WNP: "Naga",
    WNR: null,
    WNS: "Nawabashah",
    WNZ: "Wenzhou",
    WOE: "Bergen Op Zoom",
    WOL: "Albion Park Rail",
    WOS: "Wonsan",
    WPC: "Pincher Creek",
    WPR: "Porvenir",
    WPU: "Puerto Williams",
    WRB: "Warner Robins",
    WRE: null,
    WRG: "Wrangell",
    WRI: "Wrightstown",
    WRL: "Worland",
    WRO: "WrocÅ‚aw",
    WRT: "Warton",
    WSZ: null,
    WTB: "Toowoomba",
    WTK: "Noatak",
    WTN: "Waddington",
    WUH: "Wuhan",
    WUN: null,
    WUS: "Wuyishan",
    WUU: "Wau",
    WUX: "Wuxi",
    WUZ: "Tangbu",
    WVB: "Walvis Bay",
    WVK: "Manakara",
    WWA: "Wasilla",
    WWD: "Wildwood",
    WWK: "Wewak",
    WWR: "Woodward",
    WWY: "West Wyalong",
    WYA: "Whyalla",
    WYE: "Yengema",
    WYS: "West Yellowstone",
    XAI: "Xinyang",
    XAP: "ChapecÃ³",
    XBJ: "Birjand",
    XCH: "Flying Fish Cove",
    XCR: "Vatry",
    XEN: "Xingcheng, Huludao",
    XFN: "Xiangyang",
    XFW: "Hamburg",
    XGN: "Xangongo",
    XGR: "Kangiqsualujjuaq",
    XIC: "Xichang",
    XIJ: "Ahmed Al Jaber AB",
    XIL: "Xilinhot",
    XIY: "Xi'an",
    XJD: "Ar Rayyan",
    XJM: "Mangla",
    XKS: "Kasabonika",
    XLB: "Lac Brochet",
    XLS: "Saint Louis",
    XMH: null,
    XMN: "Xiamen",
    XMS: "Macas",
    XNA: "Fayetteville/Springdale/Rogers",
    XNH: "Nasiriyah",
    XNN: "Xining",
    XPK: "Pukatawagan",
    XPL: "Tegucigalpa",
    XPP: "Poplar River",
    XQP: "Quepos",
    XRH: "Richmond",
    XRR: "Ross River",
    XRY: "Jerez de la Frontera",
    XSB: "Sir Bani Yas",
    XSC: "South Caicos",
    XSI: "South Indian Lake",
    XSP: "Seletar",
    XTG: null,
    XTL: "Tadoule Lake",
    XUZ: "Xuzhou",
    XWA: "Williston",
    XXN: "Riyadh",
    YAC: "Cat Lake",
    YAG: "Fort Frances",
    YAH: "La Grande-4",
    YAI: "Chillan",
    YAK: "Yakutat",
    YAL: "Alert Bay",
    YAM: "Sault Ste Marie",
    YAO: "YaoundÃ©",
    YAP: "Yap Island",
    YAT: "Attawapiskat",
    YAY: "St. Anthony",
    YAZ: "Tofino",
    YBB: "Kugaaruk",
    YBC: "Baie-Comeau",
    YBE: "Uranium City",
    YBG: "Bagotville",
    YBK: "Baker Lake",
    YBL: "Campbell River",
    YBP: "Yibin",
    YBR: "Brandon",
    YBT: "Brochet",
    YBV: "Berens River",
    YBX: "Lourdes-de-Blanc-Sablon",
    YBY: "Bonnyville",
    YCB: "Cambridge Bay",
    YCC: "Cornwall",
    YCD: "Nanaimo",
    YCE: "Huron Park",
    YCG: "Castlegar",
    YCH: "Miramichi",
    YCL: "Charlo",
    YCM: "St Catharines",
    YCN: "Cochrane",
    YCO: "Kugluktuk",
    YCQ: "Chetwynd",
    YCR: "Cross Lake",
    YCS: "Chesterfield Inlet",
    YCY: "Clyde River",
    YDA: "Dawson City",
    YDB: "Burwash",
    YDF: "Deer Lake",
    YDG: "Digby",
    YDN: "Dauphin",
    YDO: "Dolbeau-St-FÃ©licien",
    YDP: "Nain",
    YDQ: "Dawson Creek",
    YDT: "Vancouver",
    YEC: "Yecheon-ri",
    YEG: "Edmonton",
    YEI: "Bursa",
    YEK: "Arviat",
    YEL: "Elliot Lake",
    YEM: "Sheguiandah",
    YEN: "Estevan",
    YEO: "Yeovil",
    YER: "Fort Severn",
    YES: "Yasouj",
    YET: "Edson",
    YEV: "Inuvik",
    YEY: "Amos",
    YFA: "Fort Albany",
    YFB: "Iqaluit",
    YFC: "Fredericton",
    YFE: "Forestville",
    YFH: "Fort Hope",
    YFO: "Flin Flon",
    YFR: "Fort Resolution",
    YFS: "Fort Simpson",
    YGB: "Texada",
    YGH: "Fort Good Hope",
    YGJ: "Yonago",
    YGK: "Kingston",
    YGL: "La Grande RiviÃ¨re",
    YGM: "Gimli",
    YGO: "Gods Lake Narrows",
    YGP: "GaspÃ©",
    YGQ: "Geraldton",
    YGR: "ÃŽles-de-la-Madeleine",
    YGT: "Igloolik",
    YGV: "Havre-Saint-Pierre",
    YGW: "Kuujjuarapik",
    YGX: "Gillam",
    YGZ: "Grise Fiord",
    YHD: "Dryden",
    YHE: "Hope",
    YHF: "Hearst",
    YHI: "Ulukhaktok",
    YHK: "Gjoa Haven",
    YHM: "Hamilton",
    YHN: "Hornepayne",
    YHO: "Hopedale",
    YHR: "Chevery",
    YHT: "Haines Junction",
    YHU: "MontrÃ©al",
    YHY: "Hay River",
    YHZ: "Halifax",
    YIA: "Yogyakarta",
    YIB: "Atikokan",
    YIC: "Yichun",
    YIE: "Arxan",
    YIF: "St-Augustin",
    YIH: "Yichang",
    YIK: "Ivujivik",
    YIO: "Pond Inlet",
    YIP: "Detroit",
    YIV: "Island Lake",
    YIW: "Yiwu",
    YJF: "Fort Liard",
    YJN: "St Jean",
    YJT: "Stephenville",
    YKA: "Kamloops",
    YKF: "Kitchener",
    YKG: "Kangirsuk",
    YKH: "Laobian, Yingkou",
    YKJ: "Key Lake",
    YKL: "Schefferville",
    YKM: "Yakima",
    YKN: "Yankton",
    YKO: "Hakkari",
    YKQ: "Waskaganish",
    YKS: "Yakutsk",
    YKX: "Kirkland Lake",
    YKY: "Kindersley",
    YKZ: "Toronto",
    YLC: "Kimmirut",
    YLD: "Chapleau",
    YLH: "Lansdowne House",
    YLI: null,
    YLJ: "Meadow Lake",
    YLL: "Lloydminster",
    YLR: "Leaf Rapids",
    YLT: "Alert",
    YLW: "Kelowna",
    YLX: "Yulin Fumian",
    YMA: "Mayo",
    YME: "Matane",
    YMG: "Manitouwadge",
    YMH: "Mary's Harbour",
    YMJ: "Moose Jaw",
    YML: "Charlevoix",
    YMM: "Fort McMurray",
    YMN: "Makkovik",
    YMO: "Moosonee",
    YMS: "Yurimaguas",
    YMT: "Chibougamau",
    YMX: "MontrÃ©al",
    YNA: "Natashquan",
    YNB: "Yanbu",
    YNC: "Wemindji",
    YND: "Gatineau",
    YNE: "Norway House",
    YNG: "Youngstown/Warren",
    YNJ: "Yanji",
    YNL: "Points North Landing",
    YNM: "Matagami",
    YNS: "Nemiscau",
    YNT: "Yantai",
    YNY: "Gonghang-ro",
    YOA: "Ekati",
    YOC: "Old Crow",
    YOD: "Cold Lake",
    YOH: "Oxford House",
    YOJ: "High Level",
    YOL: "Yola",
    YOO: "Oshawa",
    YOP: "Rainbow Lake",
    YOS: "Owen Sound",
    YOW: "Ottawa",
    YPA: "Prince Albert",
    YPC: "Paulatuk",
    YPE: "Peace River",
    YPG: "Portage la Prairie",
    YPH: "Inukjuak",
    YPJ: "Aupaluk",
    YPL: "Pickle Lake",
    YPM: "Pikangikum",
    YPN: "Port-Menier",
    YPO: "Peawanuck",
    YPQ: "Peterborough",
    YPR: "Prince Rupert",
    YPS: "Port Hawkesbury",
    YPW: "Powell River",
    YPX: "Puvirnituq",
    YPY: "Fort Chipewyan",
    YQA: "Muskoka",
    YQB: "Quebec",
    YQC: "Quaqtaq",
    YQD: "The Pas",
    YQF: "Springbrook",
    YQG: "Windsor",
    YQH: "Watson Lake",
    YQI: "Yarmouth",
    YQK: "Kenora",
    YQL: "Lethbridge",
    YQM: "Moncton",
    YQN: "Nakina",
    YQQ: "Comox",
    YQR: "Regina",
    YQS: "St Thomas",
    YQT: "Thunder Bay",
    YQU: "Grande Prairie",
    YQV: "Yorkton",
    YQW: "North Battleford",
    YQX: "Gander",
    YQY: "Sydney",
    YQZ: "Quesnel",
    YRA: "GamÃ¨tÃ¬",
    YRB: "Resolute Bay",
    YRF: "Cartwright",
    YRI: "RiviÃ¨re-du-Loup",
    YRJ: "Roberval",
    YRL: "Red Lake",
    YRO: "Ottawa",
    YRQ: "Trois-RiviÃ¨res",
    YRS: "Red Sucker Lake",
    YRT: "Rankin Inlet",
    YRV: "Revelstoke",
    YSB: "Sudbury",
    YSC: "Sherbrooke",
    YSF: "Stony Rapids",
    YSG: "Lutselk'e",
    YSH: "Smiths Falls",
    YSJ: "Saint John",
    YSK: "Sanikiluaq",
    YSL: "St Leonard",
    YSM: "Fort Smith",
    YSN: "Salmon Arm",
    YSP: "Marathon",
    YSQ: "Qian Gorlos Mongol Autonomous County",
    YST: "St. Theresa Point",
    YSU: "Slemon Park",
    YSY: "Sachs Harbour",
    YTA: "Pembroke",
    YTD: "Thicket Portage",
    YTE: "Kinngait",
    YTF: "Alma",
    YTH: "Thompson",
    YTL: "Big Trout Lake",
    YTM: "La Macaza",
    YTQ: "Tasiujaq",
    YTR: "Trenton",
    YTS: "Timmins",
    YTY: "Yangzhou",
    YTZ: "Toronto",
    YUA: "Yuanmou",
    YUB: "Tuktoyaktuk",
    YUD: "Umiujaq",
    YUL: "MontrÃ©al",
    YUM: "Yuma",
    YUS: "Yushu",
    YUT: "Repulse Bay",
    YUX: "Sanirajak",
    YUY: "Rouyn-Noranda",
    YVB: "Bonaventure",
    YVC: "La Ronge",
    YVE: "Vernon",
    YVM: "Qikiqtarjuaq",
    YVO: "Val-d'Or",
    YVP: "Kuujjuaq",
    YVQ: "Norman Wells",
    YVR: "Vancouver",
    YVV: "Wiarton",
    YVZ: "Deer Lake",
    YWA: "Petawawa",
    YWB: "Kangiqsujuaq",
    YWG: "Winnipeg",
    YWJ: "DÃ©line",
    YWK: "Wabush",
    YWL: "Williams Lake",
    YWP: "Webequie",
    YWY: "Wrigley",
    YXC: "Cranbrook",
    YXE: "Saskatoon",
    YXH: "Medicine Hat",
    YXJ: "Fort St.John",
    YXK: "Rimouski",
    YXL: "Sioux Lookout",
    YXN: "Whale Cove",
    YXP: "Pangnirtung",
    YXQ: "Beaver Creek",
    YXR: "Earlton",
    YXS: "Prince George",
    YXT: "Terrace",
    YXU: "London",
    YXX: "Abbotsford",
    YXY: "Whitehorse",
    YXZ: "Wawa",
    YYA: "Yueyang",
    YYB: "North Bay",
    YYC: "Calgary",
    YYD: "Smithers",
    YYE: "Fort Nelson",
    YYF: "Penticton",
    YYG: "Charlottetown",
    YYH: "Taloyoak",
    YYJ: "Victoria",
    YYL: "Lynn Lake",
    YYN: "Swift Current",
    YYQ: "Churchill",
    YYR: "Goose Bay",
    YYT: "St. John's",
    YYU: "Kapuskasing",
    YYW: "Armstrong",
    YYY: "Mont-Joli",
    YYZ: "Toronto",
    YZE: "Gore Bay",
    YZF: "Yellowknife",
    YZG: "Salluit",
    YZH: "Slave Lake",
    YZP: "Sandspit",
    YZR: "Sarnia",
    YZS: "Coral Harbour",
    YZT: "Port Hardy",
    YZU: "Whitecourt",
    YZV: "Sept-ÃŽles",
    YZW: "Teslin",
    YZX: "Greenwood",
    ZAC: "York Landing",
    ZAD: "Zemunik (Zadar)",
    ZAG: "Zagreb",
    ZAH: "Zahedan",
    ZAL: "Valdivia",
    ZAM: "Zamboanga City",
    ZAO: "Cahors/Lalbenque",
    ZAR: "Zaria",
    ZAZ: "Zaragoza",
    ZBF: "Bathurst",
    ZBM: "Bromont",
    ZBR: "Chabahar",
    ZCL: "Zacatecas",
    ZCO: "Temuco",
    ZEC: "Secunda",
    ZEM: "Eastmain River",
    ZER: "Ziro",
    ZFA: "Faro",
    ZFD: "Fond-Du-Lac",
    ZFM: "Fort Mcpherson",
    ZFN: "Tulita",
    ZGF: "Grand Forks",
    ZGI: "Gods River",
    ZGR: "Little Grand Rapids",
    ZGU: "Gaua Island",
    ZHA: "Zhanjiang (Xiashan)",
    ZHH: "Herschel Island (Yukon Territory)",
    ZHI: "Grenchen",
    ZHY: "Zhongwei",
    ZIA: "Moscow",
    ZIC: "Victoria",
    ZIG: "Ziguinchor",
    ZIH: "Ixtapa",
    ZIX: "Zhigansk",
    ZJG: "Jenpeg",
    ZJN: "Swan River",
    ZKE: "Kashechewan",
    ZKP: "Zyryanka",
    ZLO: "Manzanillo",
    ZMG: "Magdeburg",
    ZMT: "Masset",
    ZND: "Zinder",
    ZNE: "Newman",
    ZNZ: "Zanzibar",
    ZOS: "Osorno",
    ZPB: "Sachigo Lake",
    ZQN: "Queenstown",
    ZQZ: "Zhangjiakou",
    ZRH: "Zurich",
    ZRJ: "Round Lake",
    ZSA: "San Salvador",
    ZSE: "St Pierre",
    ZSJ: "Sandy Lake",
    ZST: "Stewart",
    ZTH: "Zakynthos Island",
    ZTM: "Shamattawa",
    ZTU: "Zaqatala",
    ZUC: "Ignace",
    ZUH: "Zhuhai (Jinwan)",
    ZVA: "Miandrivazo",
    ZVK: null,
    ZWA: null,
    ZWL: "Wollaston Lake",
    ZXT: "Baku",
    ZYI: "Zunyi",
    ZYL: "Sylhet",
    ZZU: "Mzuzu",
    ZZV: "Zanesville"
  }